import { LitElement, css, html, nothing } from "lit";
import { customElement, property } from "lit/decorators.js";
import { live } from "lit/directives/live.js";
import type { ExplorerCardConfig, ExplorerPresence, PresenceEntityBinding, ShellyPetDetectionConfig } from "../models/config";
import type { HassEntity, HomeAssistant } from "../types";

function friendlyName(entity:HassEntity):string { const value=entity.attributes.friendly_name; return typeof value==="string"&&value.trim()?value:entity.entity_id; }
function clean<T extends object>(value:T):T { return Object.fromEntries(Object.entries(value).filter(([,entry])=>entry!==undefined&&entry!=="")) as T; }

@customElement("ha-explorer-shelly-pet-editor")
export class HaExplorerShellyPetEditor extends LitElement {
  @property({attribute:false}) public hass?:HomeAssistant;
  @property({attribute:false}) public config?:ExplorerCardConfig;

  private emit(presences:ExplorerPresence[]):void { if(!this.config)return;this.dispatchEvent(new CustomEvent("config-changed",{detail:{config:{...this.config,presences}},bubbles:true,composed:true})); }
  private updatePresence(index:number,patch:Partial<ExplorerPresence>):void { const presences=[...(this.config?.presences??[])],current=presences[index];if(!current)return;presences[index]={...current,type:"pet",...patch};this.emit(presences); }
  private updateBinding(index:number,patch:Partial<PresenceEntityBinding>):void { const current=this.config?.presences?.[index];if(!current)return;this.updatePresence(index,{entity_binding:clean({...current.entity_binding,...patch})}); }
  private updateDetection(index:number,patch:Partial<ShellyPetDetectionConfig>):void { const current=this.config?.presences?.[index];if(!current)return;this.updatePresence(index,{shelly_pet_detection:clean({enabled:true,height_attribute:"maxz",target_id_attribute:"target_id",timestamp_attribute:"timestamp",max_height_m:.75,release_height_m:.95,confirmation_updates:3,release_updates:2,...current.shelly_pet_detection,...patch})}); }
  private addRabbit():void { const presences=[...(this.config?.presences??[])],ids=new Set(presences.map(p=>p.id));let n=1;while(ids.has(n===1?"kanin":`kanin_${n}`))n+=1;const id=n===1?"kanin":`kanin_${n}`;presences.push({id,name:"Kanin",type:"pet",visible:true,trail_visible:true,icon:"🐇",entity_binding:{coordinate_space:"room_meters",x_attribute:"x",y_attribute:"y"},shelly_pet_detection:{enabled:true,height_attribute:"maxz",target_id_attribute:"target_id",timestamp_attribute:"timestamp",max_height_m:.75,release_height_m:.95,confirmation_updates:3,release_updates:2}});this.emit(presences); }
  private entities():HassEntity[] { return Object.values(this.hass?.states??{}).filter(entity=>entity.entity_id.startsWith("sensor.")).sort((a,b)=>friendlyName(a).localeCompare(friendlyName(b),"da")); }
  protected render(){
    const all=this.config?.presences??[],pets=all.map((presence,index)=>({presence,index})).filter(({presence})=>(presence.type??"person")==="pet");
    return html`<section class="panel"><div class="heading"><div><span class="eyebrow">Shelly Presence Gen4 · Pet Detection</span><h3>Find kaninen med radar</h3></div><button @click=${this.addRabbit}>+ Tilføj kanin</button></div>
      <p class="intro">Bruger Shelly LiveTrack-koordinaterne og <code>maxz</code>. Et mål skal være lavt flere opdateringer i træk, før det vises som kæledyr. Høje mål skjules i stedet for at blive vist som kanin.</p>
      ${pets.length?pets.map(({presence,index})=>{const binding=presence.entity_binding??{},d=presence.shelly_pet_detection??{};return html`<article class="pet-card"><div class="pet-heading"><strong>🐇 ${presence.name??presence.id}</strong><span>${d.enabled?"Aktiv":"Deaktiveret"}</span></div>
        <label class="toggle"><input type="checkbox" .checked=${d.enabled===true} @change=${(e:Event)=>this.updateDetection(index,{enabled:(e.target as HTMLInputElement).checked})}/><span><strong>Automatisk kæledyrsregistrering</strong><small>Påvirker kun denne kæledyrsprofil.</small></span></label>
        <label>LiveTrack-entitet<input list="shelly-pet-entities" .value=${live(binding.position_entity??binding.entity??"")} placeholder="sensor.stue_presence_stuen_target_1" @change=${(e:Event)=>this.updateBinding(index,{position_entity:(e.target as HTMLInputElement).value.trim()||undefined})}/><small>Entiteten skal have attributterne x, y, maxz og helst target_id.</small></label>
        <div class="grid three"><label>Rum<select .value=${live(presence.room_id??"")} @change=${(e:Event)=>this.updatePresence(index,{room_id:(e.target as HTMLSelectElement).value||undefined})}><option value="">Vælg rum</option>${(this.config?.rooms??[]).map(room=>html`<option value=${room.id}>${room.name??room.id}</option>`)}</select></label><label>X-attribut<input .value=${live(binding.x_attribute??"x")} @change=${(e:Event)=>this.updateBinding(index,{x_attribute:(e.target as HTMLInputElement).value.trim()||"x",coordinate_space:"room_meters"})}/></label><label>Y-attribut<input .value=${live(binding.y_attribute??"y")} @change=${(e:Event)=>this.updateBinding(index,{y_attribute:(e.target as HTMLInputElement).value.trim()||"y",coordinate_space:"room_meters"})}/></label></div>
        <div class="grid three"><label>Højde-attribut<input .value=${d.height_attribute??"maxz"} @change=${(e:Event)=>this.updateDetection(index,{height_attribute:(e.target as HTMLInputElement).value.trim()||"maxz"})}/></label><label>Target-ID-attribut<input .value=${d.target_id_attribute??"target_id"} @change=${(e:Event)=>this.updateDetection(index,{target_id_attribute:(e.target as HTMLInputElement).value.trim()||"target_id"})}/></label><label>Tidsstempel-attribut<input .value=${d.timestamp_attribute??"timestamp"} @change=${(e:Event)=>this.updateDetection(index,{timestamp_attribute:(e.target as HTMLInputElement).value.trim()||"timestamp"})}/></label></div>
        <div class="grid two"><label>Maks. kaninhøjde: <strong>${d.max_height_m??.75} m</strong><input type="range" min="0.15" max="1.2" step="0.05" .value=${String(d.max_height_m??.75)} @input=${(e:Event)=>this.updateDetection(index,{max_height_m:Number((e.target as HTMLInputElement).value)})}/></label><label>Skjul igen over: <strong>${d.release_height_m??.95} m</strong><input type="range" min="0.25" max="1.6" step="0.05" .value=${String(d.release_height_m??.95)} @input=${(e:Event)=>this.updateDetection(index,{release_height_m:Number((e.target as HTMLInputElement).value)})}/></label></div>
        <div class="grid two"><label>Bekræft efter målinger<input type="number" min="1" max="12" .value=${String(d.confirmation_updates??3)} @change=${(e:Event)=>this.updateDetection(index,{confirmation_updates:Number((e.target as HTMLInputElement).value)})}/><small>Flere målinger giver færre falske kaniner.</small></label><label>Skjul efter høje målinger<input type="number" min="1" max="12" .value=${String(d.release_updates??2)} @change=${(e:Event)=>this.updateDetection(index,{release_updates:Number((e.target as HTMLInputElement).value)})}/></label></div>
      </article>`;}):html`<div class="empty">Ingen kæledyrsprofil endnu. Tryk “Tilføj kanin”.</div>`}
      <datalist id="shelly-pet-entities">${this.entities().map(entity=>html`<option value=${entity.entity_id}>${friendlyName(entity)}</option>`)}</datalist>
      ${pets.length?html`<div class="note">Start med 0,75 m. Test derefter i Shellys target-visning og sænk grænsen, hvis et menneske på gulvet bliver registreret som kanin.</div>`:nothing}
    </section>`;
  }
  static styles=css`:host{display:block}.panel{display:grid;gap:14px;margin-top:12px;padding:16px;border:1px solid var(--divider-color);border-radius:12px;background:var(--card-background-color)}.heading,.pet-heading{display:flex;align-items:center;justify-content:space-between;gap:12px}.eyebrow{color:var(--secondary-text-color);font-size:.72rem;letter-spacing:.08em;text-transform:uppercase}h3{margin:3px 0 0;font-size:1rem}button{border:0;border-radius:10px;padding:10px 13px;background:var(--primary-color,#03a9f4);color:var(--text-primary-color,#fff);font-weight:700}.intro,p,small{margin:0;color:var(--secondary-text-color);font-size:.8rem;line-height:1.45}.pet-card{display:grid;gap:13px;padding:14px;border:1px solid var(--divider-color);border-radius:11px}.pet-heading span{font-size:.72rem;color:var(--secondary-text-color)}label{display:grid;gap:6px;font-weight:600}.grid{display:grid;gap:10px}.two{grid-template-columns:repeat(2,minmax(0,1fr))}.three{grid-template-columns:repeat(3,minmax(0,1fr))}input,select{box-sizing:border-box;width:100%;min-height:40px;padding:8px;border:1px solid var(--divider-color);border-radius:8px;background:var(--card-background-color);color:var(--primary-text-color)}input[type="range"]{padding:0}.toggle{grid-template-columns:auto 1fr;align-items:start;padding:10px;background:var(--secondary-background-color);border-radius:9px}.toggle input{width:auto;min-height:0;margin-top:3px}.toggle span{display:grid;gap:2px}.note,.empty{padding:11px;border-radius:9px;background:var(--secondary-background-color);font-size:.8rem}@media(max-width:600px){.heading{align-items:flex-start;flex-direction:column}.two,.three{grid-template-columns:1fr}}`;
}
