import { LitElement, css, html, nothing, svg } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { unsafeSVG } from "lit/directives/unsafe-svg.js";
import "./explorer-room-panel";
import type { ExplorerPresence, ExplorerRoom, FloorplanFitMode, FloorplanMetadata, PresenceObjectType, ViewportState } from "../models/config";
import type { HomeAssistant } from "../types";
import { VIEWBOX_SIZE, clampViewport, clampZoom, viewportTransform, zoomAroundPoint } from "../utils/viewport";
const DEFAULT_METADATA:FloorplanMetadata={width:16,height:9,status:"idle"};
const DEFAULT_ICONS:Record<PresenceObjectType,string>={person:"●",pet:"◆",robot:"■",vehicle:"▰",object:"✦"};
const BLOCKED_SVG_ELEMENTS="script,foreignObject,iframe,object,embed,link,meta,audio,video,canvas";
function isSvgSource(source:string):boolean{try{return new URL(source,window.location.href).pathname.toLowerCase().endsWith(".svg");}catch{return source.split(/[?#]/,1)[0].toLowerCase().endsWith(".svg");}}
function parseSvgLength(value:string|null):number|undefined{if(!value)return;const match=value.trim().match(/^(-?\d+(?:\.\d+)?)/);if(!match)return;const number=Number(match[1]);return Number.isFinite(number)&&number>0?number:undefined;}
function readSvgDimensions(svgElement:SVGSVGElement){const viewBox=svgElement.getAttribute("viewBox")?.trim().split(/[\s,]+/).map(Number);if(viewBox?.length===4&&viewBox.every(Number.isFinite)&&viewBox[2]>0&&viewBox[3]>0)return{width:viewBox[2],height:viewBox[3]};return{width:parseSvgLength(svgElement.getAttribute("width"))??16,height:parseSvgLength(svgElement.getAttribute("height"))??9};}
function sanitizeCss(cssText:string):string{return cssText.replace(/@import[^;]+;?/gi,"").replace(/url\(([^)]*)\)/gi,(_match,rawReference:string)=>{const reference=rawReference.trim().replace(/^['"]|['"]$/g,"");return reference.startsWith("#")?`url(${reference})`:"none";}).replace(/javascript\s*:/gi,"").replace(/expression\s*\(/gi,"");}
function isSafeSvgReference(value:string):boolean{const reference=value.trim();return reference===""||reference.startsWith("#")||/^data:image\/(?:png|jpe?g|gif|webp|svg\+xml);base64,/i.test(reference);}
function safePresenceAvatar(source?:string):string|undefined{const value=source?.trim();if(!value)return;if(/^data:image\/(?:png|jpe?g|gif|webp);base64,/i.test(value))return value;if(value.startsWith("/"))return value;try{const url=new URL(value,window.location.href);if(["http:","https:","blob:"].includes(url.protocol))return value;}catch{return;}return;}
function sanitizeSvgDocument(document:Document):SVGSVGElement{const parserError=document.querySelector("parsererror"),root=document.documentElement;if(parserError||root.localName.toLowerCase()!=="svg")throw new Error("Filen indeholder ikke gyldig SVG-kode.");root.querySelectorAll(BLOCKED_SVG_ELEMENTS).forEach(element=>element.remove());const elements=[root,...Array.from(root.querySelectorAll("*"))];for(const element of elements){for(const attribute of Array.from(element.attributes)){const name=attribute.name.toLowerCase(),value=attribute.value;if(name.startsWith("on")){element.removeAttribute(attribute.name);continue;}if((name==="href"||name==="xlink:href")&&!isSafeSvgReference(value)){element.removeAttribute(attribute.name);continue;}if(name==="style"){const cleanedStyle=sanitizeCss(value).trim();if(cleanedStyle)element.setAttribute(attribute.name,cleanedStyle);else element.removeAttribute(attribute.name);}}}root.querySelectorAll("style").forEach(styleElement=>{const cleanedCss=sanitizeCss(styleElement.textContent??"").trim();if(cleanedCss)styleElement.textContent=cleanedCss;else styleElement.remove();});if(!root.hasAttribute("xmlns"))root.setAttribute("xmlns","http://www.w3.org/2000/svg");return root as unknown as SVGSVGElement;}
@customElement("explorer-canvas")
export class ExplorerCanvas extends LitElement{
 @property({attribute:false}) public hass?:HomeAssistant;@property() image="";@property({attribute:false}) rooms:ExplorerRoom[]=[];@property({attribute:false}) presences:ExplorerPresence[]=[];@property({type:Number,attribute:"min-zoom"}) minZoom=1;@property({type:Number,attribute:"max-zoom"}) maxZoom=6;@property({type:Number,attribute:"initial-zoom"}) initialZoom=1;@property({attribute:"fit-mode"}) fitMode:FloorplanFitMode="contain";
 @state() private viewport:ViewportState={zoom:1,x:0,y:0};@state() private selectedRoom?:ExplorerRoom;@state() private selectedPresence?:ExplorerPresence;@state() private metadata:FloorplanMetadata={...DEFAULT_METADATA};@state() private imageSource="";@state() private svgMarkup="";@state() private loadError="";private pointerId?:number;private lastPointer?:{x:number;y:number};private imageRequest=0;
 connectedCallback():void{super.connectedCallback();this.resetViewport();}
 protected updated(changed:Map<PropertyKey,unknown>):void{if(changed.has("rooms")&&this.selectedRoom)this.selectedRoom=this.rooms.find(room=>room.id===this.selectedRoom?.id);if(changed.has("image")||(changed.has("fitMode")&&this.image&&isSvgSource(this.image)))void this.loadFloorplan();}
 private async loadFloorplan():Promise<void>{const request=++this.imageRequest;this.imageSource="";this.svgMarkup="";this.loadError="";if(!this.image){this.metadata={...DEFAULT_METADATA};this.resetViewport();return;}this.metadata={...this.metadata,status:"loading"};try{if(isSvgSource(this.image))await this.loadSvgFloorplan(request);else await this.loadRasterFloorplan(request);}catch(error){if(request!==this.imageRequest)return;this.imageSource="";this.svgMarkup="";this.metadata={...this.metadata,status:"error"};this.loadError=error instanceof Error?error.message:"Plantegningen kunne ikke indlæses.";}}
 private async loadSvgFloorplan(request:number):Promise<void>{const response=await fetch(this.image,{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw new Error(`SVG-filen kunne ikke hentes (${response.status}).`);const svgText=await response.text();if(request!==this.imageRequest)return;const document=new DOMParser().parseFromString(svgText,"image/svg+xml"),svgElement=sanitizeSvgDocument(document),dimensions=readSvgDimensions(svgElement);if(!svgElement.hasAttribute("viewBox"))svgElement.setAttribute("viewBox",`0 0 ${dimensions.width} ${dimensions.height}`);svgElement.setAttribute("x","0");svgElement.setAttribute("y","0");svgElement.setAttribute("width",String(VIEWBOX_SIZE));svgElement.setAttribute("height",String(VIEWBOX_SIZE));svgElement.setAttribute("preserveAspectRatio",this.fitMode==="cover"?"xMidYMid slice":"xMidYMid meet");svgElement.setAttribute("class","inline-floorplan");const serializedSvg=new XMLSerializer().serializeToString(svgElement);if(request!==this.imageRequest)return;this.svgMarkup=serializedSvg;this.metadata={width:dimensions.width,height:dimensions.height,status:"loaded"};this.resetViewport();}
 private async loadRasterFloorplan(request:number):Promise<void>{const image=new Image();image.decoding="async";await new Promise<void>((resolve,reject)=>{image.onload=()=>{if(request!==this.imageRequest)return resolve();this.imageSource=this.image;this.metadata={width:Math.max(1,image.naturalWidth||16),height:Math.max(1,image.naturalHeight||9),status:"loaded"};this.resetViewport();resolve();};image.onerror=()=>reject(new Error("Billedfilen kunne ikke indlæses. Kontrollér filstien."));image.src=this.image;});}
 private resetViewport():void{this.viewport={zoom:clampZoom(this.initialZoom,this.minZoom,this.maxZoom),x:0,y:0};}
 private toViewBoxPoint(event:WheelEvent|PointerEvent){const svgElement=this.renderRoot.querySelector("svg.floorplan");if(!svgElement)return{x:VIEWBOX_SIZE/2,y:VIEWBOX_SIZE/2};const rect=svgElement.getBoundingClientRect();return{x:((event.clientX-rect.left)/rect.width)*VIEWBOX_SIZE,y:((event.clientY-rect.top)/rect.height)*VIEWBOX_SIZE};}
 private handleWheel(event:WheelEvent):void{event.preventDefault();const point=this.toViewBoxPoint(event),factor=event.deltaY<0?1.12:1/1.12,nextZoom=clampZoom(this.viewport.zoom*factor,this.minZoom,this.maxZoom);this.viewport=clampViewport(zoomAroundPoint(this.viewport,nextZoom,point.x,point.y),this.minZoom);}
 private handlePointerDown(event:PointerEvent):void{if(this.viewport.zoom<=this.minZoom+.0001){this.resetViewport();return;}this.pointerId=event.pointerId;this.lastPointer={x:event.clientX,y:event.clientY};(event.currentTarget as SVGElement).setPointerCapture(event.pointerId);}
 private handlePointerMove(event:PointerEvent):void{if(event.pointerId!==this.pointerId||!this.lastPointer)return;const rect=(event.currentTarget as SVGSVGElement).getBoundingClientRect(),dx=((event.clientX-this.lastPointer.x)/rect.width)*VIEWBOX_SIZE,dy=((event.clientY-this.lastPointer.y)/rect.height)*VIEWBOX_SIZE;this.viewport=clampViewport({...this.viewport,x:this.viewport.x+dx,y:this.viewport.y+dy},this.minZoom);this.lastPointer={x:event.clientX,y:event.clientY};}
 private handlePointerUp(event:PointerEvent):void{if(event.pointerId!==this.pointerId)return;this.pointerId=undefined;this.lastPointer=undefined;}
 private selectRoom(event:Event,room:ExplorerRoom):void{event.stopPropagation();this.selectedRoom=this.selectedRoom?.id===room.id?undefined:room;if(this.selectedRoom)this.selectedPresence=undefined;}
 private selectPresence(event:Event,presence:ExplorerPresence):void{event.stopPropagation();this.selectedPresence=this.selectedPresence?.id===presence.id?undefined:presence;if(this.selectedPresence)this.selectedRoom=undefined;}
 private renderRooms(){return this.rooms.map(room=>{if(!room.points.length)return nothing;const points=room.points.map(([x,y])=>`${x*VIEWBOX_SIZE},${y*VIEWBOX_SIZE}`).join(" "),selected=room.id===this.selectedRoom?.id,averageX=room.points.reduce((sum,point)=>sum+point[0],0)/room.points.length,averageY=room.points.reduce((sum,point)=>sum+point[1],0)/room.points.length,labelX=(room.label?.x??averageX)*VIEWBOX_SIZE,labelY=(room.label?.y??averageY)*VIEWBOX_SIZE,color=room.color??"#03a9f4",maskWidth=Math.max(76,Math.min(190,(room.name?.length??0)*15+28));return svg`<g class=${selected?"room selected":"room"} @pointerdown=${(event:PointerEvent)=>event.stopPropagation()} @click=${(event:MouseEvent)=>this.selectRoom(event,room)}><polygon points=${points} fill=${color} fill-opacity=${selected?"0.34":"0.18"} stroke=${color} stroke-opacity="0.9" stroke-width=${selected?"5":"3"} vector-effect="non-scaling-stroke"></polygon>${room.name?svg`<rect class="room-label-mask" x=${labelX-maskWidth/2} y=${labelY-18} width=${maskWidth} height="36" rx="10"></rect><text class="room-label" x=${labelX} y=${labelY} text-anchor="middle" dominant-baseline="middle">${room.name}</text>`:nothing}</g>`;});}
 private renderPresences(){return this.presences.filter(presence=>presence.visible!==false).map((presence,index)=>{const type=presence.type??"person",selected=presence.id===this.selectedPresence?.id,x=(presence.x??.5)*VIEWBOX_SIZE,y=(presence.y??.5)*VIEWBOX_SIZE,icon=presence.icon??DEFAULT_ICONS[type],avatar=safePresenceAvatar(presence.avatar),color=presence.color??"#03a9f4",radius=selected?31:25,diameter=radius*2,clipId=`presence-avatar-${index}`,labelY=selected?58:52;return svg`<g class=${selected?"presence selected":"presence"} transform=${`translate(${x} ${y})`} @pointerdown=${(event:PointerEvent)=>event.stopPropagation()} @click=${(event:MouseEvent)=>this.selectPresence(event,presence)}>${avatar?svg`<defs><clipPath id=${clipId}><circle r=${radius-3}></circle></clipPath></defs><circle class="presence-avatar-background" r=${radius} fill=${color}></circle><image href=${avatar} x=${-radius+3} y=${-radius+3} width=${diameter-6} height=${diameter-6} preserveAspectRatio="xMidYMid slice" clip-path=${`url(#${clipId})`}></image><circle class="presence-border" r=${radius} fill="none" stroke=${color} stroke-width=${selected?"5":"3"} vector-effect="non-scaling-stroke"></circle>`:svg`<circle class="presence-marker" r=${radius} fill=${color} fill-opacity=${selected?"1":".88"}></circle><text class="presence-icon" text-anchor="middle" dominant-baseline="middle">${icon}</text>`}<text class="presence-label" y=${labelY} text-anchor="middle">${presence.name??presence.id}</text></g>`;});}
 protected render(){const transform=viewportTransform(this.viewport);return html`<div class="viewport"><svg class="floorplan" viewBox="0 0 ${VIEWBOX_SIZE} ${VIEWBOX_SIZE}" @wheel=${this.handleWheel} @pointerdown=${this.handlePointerDown} @pointermove=${this.handlePointerMove} @pointerup=${this.handlePointerUp} @pointercancel=${this.handlePointerUp} @click=${()=>{this.selectedRoom=undefined;this.selectedPresence=undefined;}}><rect class="backdrop" width=${VIEWBOX_SIZE} height=${VIEWBOX_SIZE}></rect><g class="scene" transform=${transform}>${this.svgMarkup?svg`<g class="floorplan-source inline-source">${unsafeSVG(this.svgMarkup)}</g>`:this.imageSource?svg`<image class="floorplan-source" href=${this.imageSource} x="0" y="0" width=${VIEWBOX_SIZE} height=${VIEWBOX_SIZE} preserveAspectRatio=${this.fitMode==="cover"?"xMidYMid slice":"xMidYMid meet"}></image>`:nothing}<g class="rooms-scene">${this.renderRooms()}</g><g class="presences-scene">${this.renderPresences()}</g></g></svg>${this.loadError?html`<div class="load-error">${this.loadError}</div>`:nothing}<button class="zoom-badge" type="button" title="Nulstil zoom og placering" aria-label="Nulstil zoom og placering" @click=${(event:Event)=>{event.stopPropagation();this.resetViewport();}}>⌂ &nbsp; ${Math.round(this.viewport.zoom*100)}%</button></div>${this.selectedRoom?html`<explorer-room-panel .hass=${this.hass} .room=${this.selectedRoom} @close=${()=>this.selectedRoom=undefined}></explorer-room-panel>`:nothing}`;}
 static styles=css`:host{display:block;position:relative}.viewport{position:relative;overflow:hidden;background:var(--secondary-background-color);touch-action:none;max-height:var(--explorer-viewport-max-height,none)}svg.floorplan{display:block;width:100%;height:auto;aspect-ratio:1/1;user-select:none}.backdrop{fill:var(--card-background-color,#fff)}.floorplan-source{pointer-events:none}.inline-source{pointer-events:none}.room{cursor:pointer}.room polygon{transition:fill-opacity .18s ease,stroke-width .18s ease}.room-label-mask{fill:transparent;pointer-events:none}.room-label{font-size:18px;font-weight:700;fill:var(--primary-text-color);paint-order:stroke;stroke:var(--card-background-color,#fff);stroke-width:4px;stroke-linejoin:round;pointer-events:none}.presence{cursor:pointer}.presence-icon{font-size:24px;fill:#fff;pointer-events:none}.presence-label{font-size:16px;font-weight:700;fill:var(--primary-text-color);paint-order:stroke;stroke:var(--card-background-color,#fff);stroke-width:4px;stroke-linejoin:round;pointer-events:none}.zoom-badge{position:absolute;right:14px;bottom:14px;padding:8px 12px;border:0;border-radius:999px;background:rgba(0,0,0,.66);color:#fff;font:inherit;font-size:.8rem;font-weight:700;cursor:pointer;touch-action:manipulation}.zoom-badge:focus-visible{outline:2px solid var(--primary-color,#03a9f4);outline-offset:2px}.load-error{position:absolute;left:14px;right:14px;top:14px;padding:10px 12px;border-radius:10px;background:var(--error-color,#db4437);color:#fff;font-size:.85rem;font-weight:700}@media(max-width:600px){.room-label{font-size:16px}.presence-label{font-size:14px}.zoom-badge{right:10px;bottom:10px}}`;
}
