import { LitElement, css, html, nothing, svg, type TemplateResult } from "lit";
import { customElement, property, query, state } from "lit/decorators.js";
import type { ExplorerCalibrationPoint, ExplorerCardConfig, ExplorerPresence, ExplorerRoom, NormalizedPoint } from "../models/config";
import type { AreaRegistryEntry, HomeAssistant } from "../types";
import { HaExplorerCardEditor } from "./explorer-config-editor";
const VIEWBOX_SIZE=1000; type DrawingMode="idle"|"draw-new"|"redraw"|"anchor"|"cal-a"|"cal-b"; type AnchorPoint={x:number;y:number}; const clamp=(v:number)=>Math.min(1,Math.max(0,v));
function roomCenter(points:NormalizedPoint[]):AnchorPoint{return points.length?{x:points.reduce((s,p)=>s+p[0],0)/points.length,y:points.reduce((s,p)=>s+p[1],0)/points.length}:{x:.5,y:.5};} function roomBounds(room:ExplorerRoom){const xs=room.points.map(p=>p[0]),ys=room.points.map(p=>p[1]);return{minX:Math.min(...xs),minY:Math.min(...ys),maxX:Math.max(...xs),maxY:Math.max(...ys)};} function finite(v:unknown){const n=typeof v==="number"?v:Number(v);return Number.isFinite(n)?n:undefined;}
@customElement("ha-explorer-room-drawing-editor") export class HaExplorerRoomDrawingEditor extends LitElement{
@property({attribute:false}) public hass?:HomeAssistant; @state() private roomConfig?:ExplorerCardConfig; @state() private drawingMode:DrawingMode="idle"; @state() private selectedRoomId=""; @state() private pendingPoints:NormalizedPoint[]=[]; @state() private pendingAnchor?:AnchorPoint; @state() private draftWidth=""; @state() private draftHeight=""; @state() private draftFlipX=false; @state() private draftFlipY=false; @state() private calA?:ExplorerCalibrationPoint; @state() private calB?:ExplorerCalibrationPoint; @state() private calibrationMessage=""; @state() private drawingAreas:AreaRegistryEntry[]=[]; @query("ha-explorer-card-editor") private baseEditor?:HaExplorerCardEditor;
public setConfig(c:ExplorerCardConfig){this.roomConfig=c;} protected updated(changed:Map<PropertyKey,unknown>){if(changed.has("hass"))void this.loadDrawingAreas();if(this.roomConfig)this.baseEditor?.setConfig(this.roomConfig);} private async loadDrawingAreas(){try{this.drawingAreas=this.hass?.callWS?[...(await this.hass.callWS<AreaRegistryEntry[]>({type:"config/area_registry/list"}))]:[];}catch{this.drawingAreas=[];}} private emitConfig(c:ExplorerCardConfig){this.roomConfig=c;this.dispatchEvent(new CustomEvent("config-changed",{detail:{config:c},bubbles:true,composed:true}));} private get rooms(){return this.roomConfig?.rooms??[];} private get selectedRoom(){return this.rooms.find(r=>r.id===this.selectedRoomId);} private mapPoint(e:MouseEvent):NormalizedPoint{const r=(e.currentTarget as SVGSVGElement).getBoundingClientRect();return [clamp((e.clientX-r.left)/r.width),clamp((e.clientY-r.top)/r.height)];}
private selectedPresence():ExplorerPresence|undefined{const ps=this.roomConfig?.presences??[];const room=this.selectedRoom;if(!room)return undefined;const candidates=ps.filter(p=>p.entity_binding?.coordinate_space==="room_meters"&&p.entity_binding.entity);const exact=candidates.find(p=>p.room_id===room.id);if(exact)return exact;if(candidates.length===1)return candidates[0];const refs=new Set([room.id,room.name??"",...(room.aliases??[])].map(x=>x.trim().toLowerCase()).filter(Boolean));return candidates.find(p=>p.room_id&&refs.has(p.room_id.trim().toLowerCase()));}
private captureCalibration(global:NormalizedPoint){const room=this.selectedRoom,p=this.selectedPresence(),h=this.hass;if(!room||!p||!h)return;const b=p.entity_binding!,e=h.states[b.entity!],m=room.physical_meters;if(!e||!m)return;const mx=finite(e.attributes[b.x_attribute??"map_x"]),my=finite(e.attributes[b.y_attribute??"map_y"]);if(mx===undefined||my===undefined)return;const rb=roomBounds(room);return{sensor_x:m.flip_x?m.width-mx:mx,sensor_y:m.flip_y?m.height-my:my,room_x:clamp((global[0]-rb.minX)/(rb.maxX-rb.minX||1)),room_y:clamp((global[1]-rb.minY)/(rb.maxY-rb.minY||1))};}
private handleMapClick(e:MouseEvent){const p=this.mapPoint(e);if(this.drawingMode==="anchor")this.pendingAnchor={x:p[0],y:p[1]};else if(this.drawingMode==="cal-a"||this.drawingMode==="cal-b"){const c=this.captureCalibration(p);if(!c){this.calibrationMessage="Kunne ikke læse live map_x/map_y.";return;}if(this.drawingMode==="cal-a")this.calA=c;else this.calB=c;this.calibrationMessage=`Punkt ${this.drawingMode==="cal-a"?"A":"B"} gemt.`;this.drawingMode="idle";}}
private selectRoom(e:MouseEvent,id:string){if(this.drawingMode!=="idle")return;e.stopPropagation();this.selectedRoomId=id;const r=this.selectedRoom;this.draftWidth=String(r?.physical_meters?.width??"");this.draftHeight=String(r?.physical_meters?.height??"");this.draftFlipX=!!r?.physical_meters?.flip_x;this.draftFlipY=!!r?.physical_meters?.flip_y;this.calA=r?.physical_meters?.position_calibration?.a;this.calB=r?.physical_meters?.position_calibration?.b;}
private meters(){const width=Number(this.draftWidth.replace(",",".")),height=Number(this.draftHeight.replace(",","."));return width>0&&height>0?{width,height,flip_x:this.draftFlipX,flip_y:this.draftFlipY,...(this.calA&&this.calB?{position_calibration:{a:this.calA,b:this.calB}}:{})}:undefined;} private saveMeters(){if(!this.roomConfig||!this.selectedRoom)return;const physical_meters=this.meters();if(physical_meters)this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,physical_meters}:r)});} private savePositionCalibration(){if(!this.roomConfig||!this.selectedRoom||!this.calA||!this.calB)return;const m=this.selectedRoom.physical_meters;if(!m)return;this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,physical_meters:{...m,position_calibration:{a:this.calA!,b:this.calB!}}}:r)});this.calibrationMessage="2-punktskalibrering gemt.";} private resetPositionCalibration(){if(!this.roomConfig||!this.selectedRoom?.physical_meters)return;const{position_calibration:_,...rest}=this.selectedRoom.physical_meters;this.calA=undefined;this.calB=undefined;this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,physical_meters:rest}:r)});}
private renderRoomPolygon(r:ExplorerRoom){const pts=r.points.map(([x,y])=>`${x*VIEWBOX_SIZE},${y*VIEWBOX_SIZE}`).join(" "),c=roomCenter(r.points),sel=r.id===this.selectedRoomId;return svg`<g @click=${(e:MouseEvent)=>this.selectRoom(e,r.id)}><polygon points=${pts} fill="var(--primary-color)" fill-opacity=${sel ? .3 : .14} stroke="var(--primary-color)" stroke-width=${sel?7:4}/><text x=${c.x*1000} y=${c.y*1000} text-anchor="middle">${r.name??r.id}</text></g>`;} private dimensionFields(){return html`<div class="dimensions"><label>Bredde (m)<input .value=${this.draftWidth} @input=${(e:InputEvent)=>this.draftWidth=(e.target as HTMLInputElement).value}></label><label>Længde (m)<input .value=${this.draftHeight} @input=${(e:InputEvent)=>this.draftHeight=(e.target as HTMLInputElement).value}></label><label><input type="checkbox" .checked=${this.draftFlipX} @change=${(e:Event)=>this.draftFlipX=(e.target as HTMLInputElement).checked}> Vend vandret (X)</label><label><input type="checkbox" .checked=${this.draftFlipY} @change=${(e:Event)=>this.draftFlipY=(e.target as HTMLInputElement).checked}> Vend lodret (Y)</label><button @click=${this.saveMeters}>Gem rumkalibrering</button></div>`;} private positionCalibration(){const p=this.selectedPresence();return html`<div class="position-cal"><strong>2-punkts positionskalibrering</strong><span>${p?`Live target: ${p.name??p.id}`:"Bind først et room_meters-target til rummet."}</span><div>Punkt A: ${this.calA?"✓ gemt":"ikke gemt"} · Punkt B: ${this.calB?"✓ gemt":"ikke gemt"}</div><div class="buttons"><button ?disabled=${!p} @click=${()=>this.drawingMode="cal-a"}>Gem punkt A</button><button ?disabled=${!p} @click=${()=>this.drawingMode="cal-b"}>Gem punkt B</button><button ?disabled=${!this.calA||!this.calB} @click=${this.savePositionCalibration}>Gem 2-punktskalibrering</button><button @click=${this.resetPositionCalibration}>Nulstil</button></div><small>${this.calibrationMessage}</small></div>`;}
protected renderRoomDrawingEditor():TemplateResult<1>{if(!this.roomConfig)return html``;const image=this.roomConfig.image??this.roomConfig.background??"";return html`<section class="drawing-editor"><div><small>VISUAL POSITION CALIBRATION · v0.33.2</small><h3>Tegn, mål, orientér og finjustér live-positioner</h3></div>${this.selectedRoom?html`${this.dimensionFields()}${this.positionCalibration()}`:nothing}<div class="map-frame"><svg viewBox="0 0 1000 1000" preserveAspectRatio="none" @click=${this.handleMapClick}><image href=${image} width="1000" height="1000" preserveAspectRatio="xMidYMid meet"/>${this.rooms.map(r=>this.renderRoomPolygon(r))}</svg></div><div class="buttons"><button @click=${()=>{this.drawingMode="idle"}}>Annuller</button></div></section>`;} protected render(){return this.renderRoomDrawingEditor();}
static styles=css`:host{display:block}.drawing-editor{display:grid;gap:14px;padding:16px}.dimensions{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.position-cal{display:grid;gap:8px;padding:12px;background:var(--secondary-background-color);border-radius:10px}.map-frame{border:1px solid var(--divider-color);border-radius:12px;overflow:hidden}svg{width:100%;height:min(58vh,620px)}text{fill:var(--primary-text-color);font-size:24px;font-weight:700}.buttons{display:flex;gap:8px;flex-wrap:wrap}button,input{padding:9px}label{display:grid;gap:5px}`;}
}