import { LitElement, css, html, nothing, svg, type TemplateResult } from "lit";
import { customElement, property, query, state } from "lit/decorators.js";
import type { ExplorerCalibrationPoint, ExplorerCardConfig, ExplorerPresence, ExplorerRoom, NormalizedPoint } from "../models/config";
import type { AreaRegistryEntry, HomeAssistant } from "../types";
import { HaExplorerCardEditor } from "./explorer-config-editor";

const VIEWBOX_SIZE=1000;
type DrawingMode="idle"|"draw-new"|"redraw"|"anchor"|"cal-a"|"cal-b";
type AnchorPoint={x:number;y:number};
const clamp=(v:number)=>Math.min(1,Math.max(0,v));
function roomCenter(points:NormalizedPoint[]):AnchorPoint{return points.length?{x:points.reduce((s,p)=>s+p[0],0)/points.length,y:points.reduce((s,p)=>s+p[1],0)/points.length}:{x:.5,y:.5};}
function roomBounds(room:ExplorerRoom){const xs=room.points.map(p=>p[0]),ys=room.points.map(p=>p[1]);return{minX:Math.min(...xs),minY:Math.min(...ys),maxX:Math.max(...xs),maxY:Math.max(...ys)};}
function slugify(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"room";}
function finite(value:unknown):number|undefined{const n=typeof value==="number"?value:Number(value);return Number.isFinite(n)?n:undefined;}

@customElement("ha-explorer-room-drawing-editor")
export class HaExplorerRoomDrawingEditor extends LitElement{
 @property({attribute:false}) public hass?:HomeAssistant;
 @state() private roomConfig?:ExplorerCardConfig;
 @state() private drawingMode:DrawingMode="idle";
 @state() private selectedRoomId="";
 @state() private pendingPoints:NormalizedPoint[]=[];
 @state() private pendingAnchor?:AnchorPoint;
 @state() private draftRoomName="";
 @state() private draftAreaId="";
 @state() private draftWidth="";
 @state() private draftHeight="";
 @state() private draftFlipX=false;
 @state() private draftFlipY=false;
 @state() private calA?:ExplorerCalibrationPoint;
 @state() private calB?:ExplorerCalibrationPoint;
 @state() private calibrationMessage="";
 @state() private drawingAreas:AreaRegistryEntry[]=[];
 @state() private drawingAreaError="";
 @query("ha-explorer-card-editor") private baseEditor?:HaExplorerCardEditor;

 public setConfig(config:ExplorerCardConfig){this.roomConfig=config;if(this.selectedRoomId&&!(config.rooms??[]).some(r=>r.id===this.selectedRoomId)){this.selectedRoomId="";this.drawingMode="idle";}}
 protected updated(changed:Map<PropertyKey,unknown>){if(changed.has("hass"))void this.loadDrawingAreas();if((changed.has("roomConfig")||changed.has("hass"))&&this.roomConfig)this.baseEditor?.setConfig(this.roomConfig);}
 private async loadDrawingAreas(){if(!this.hass?.callWS){this.drawingAreas=[];return;}try{this.drawingAreas=[...(await this.hass.callWS<AreaRegistryEntry[]>({type:"config/area_registry/list"}))].sort((a,b)=>a.name.localeCompare(b.name,"da"));}catch{this.drawingAreaError="Home Assistant Areas kunne ikke hentes.";}}
 private handleBaseConfigChanged(e:CustomEvent<{config:ExplorerCardConfig}>){if(!e.detail?.config)return;e.stopPropagation();this.emitConfig(e.detail.config);}
 private emitConfig(config:ExplorerCardConfig){this.roomConfig=config;this.baseEditor?.setConfig(config);this.dispatchEvent(new CustomEvent("config-changed",{detail:{config},bubbles:true,composed:true}));}
 private get rooms(){return this.roomConfig?.rooms??[];}
 private get selectedRoom(){return this.rooms.find(r=>r.id===this.selectedRoomId);}
 private mapPoint(e:MouseEvent):NormalizedPoint{const r=(e.currentTarget as SVGSVGElement).getBoundingClientRect();return r.width&&r.height?[clamp((e.clientX-r.left)/r.width),clamp((e.clientY-r.top)/r.height)]:[.5,.5];}
 private selectedPresence():ExplorerPresence|undefined{return (this.roomConfig?.presences??[]).find(p=>p.room_id===this.selectedRoomId&&p.entity_binding?.coordinate_space==="room_meters"&&p.entity_binding.entity);}
 private captureCalibration(global:NormalizedPoint):ExplorerCalibrationPoint|undefined{const room=this.selectedRoom,presence=this.selectedPresence(),hass=this.hass;if(!room||!presence||!hass)return undefined;const binding=presence.entity_binding!,entity=hass.states[binding.entity!];if(!entity)return undefined;const mx=finite(entity.attributes[binding.x_attribute??"map_x"]),my=finite(entity.attributes[binding.y_attribute??"map_y"]),meters=room.physical_meters;if(mx===undefined||my===undefined||!meters)return undefined;const b=roomBounds(room),roomX=clamp((global[0]-b.minX)/(b.maxX-b.minX||1)),roomY=clamp((global[1]-b.minY)/(b.maxY-b.minY||1));return{sensor_x:meters.flip_x?meters.width-mx:mx,sensor_y:meters.flip_y?meters.height-my:my,room_x:roomX,room_y:roomY};}
 private handleMapClick(e:MouseEvent){const p=this.mapPoint(e);if(this.drawingMode==="draw-new"||this.drawingMode==="redraw")this.pendingPoints=[...this.pendingPoints,p];else if(this.drawingMode==="anchor"&&this.selectedRoom)this.pendingAnchor={x:p[0],y:p[1]};else if(this.drawingMode==="cal-a"||this.drawingMode==="cal-b"){const point=this.captureCalibration(p);if(!point){this.calibrationMessage="Kunne ikke læse live map_x/map_y. Kontroller Target-bindingen.";return;}if(this.drawingMode==="cal-a")this.calA=point;else this.calB=point;this.calibrationMessage=`Punkt ${this.drawingMode==="cal-a"?"A":"B"} gemt fra den aktuelle sensorposition.`;this.drawingMode="idle";}}
 private selectRoom(e:MouseEvent,id:string){if(this.drawingMode!=="idle")return;e.stopPropagation();this.selectedRoomId=id;const r=this.rooms.find(x=>x.id===id);this.draftWidth=r?.physical_meters?.width?.toString()??"";this.draftHeight=r?.physical_meters?.height?.toString()??"";this.draftFlipX=r?.physical_meters?.flip_x??false;this.draftFlipY=r?.physical_meters?.flip_y??false;this.calA=r?.physical_meters?.position_calibration?.a;this.calB=r?.physical_meters?.position_calibration?.b;this.calibrationMessage="";}
 private uniqueRoomId(name:string){const b=slugify(name),used=new Set(this.rooms.map(r=>r.id));if(!used.has(b))return b;let n=2;while(used.has(`${b}_${n}`))n++;return`${b}_${n}`;}
 private beginNewRoom(){this.selectedRoomId="";this.pendingPoints=[];this.pendingAnchor=undefined;this.draftRoomName=`Rum ${this.rooms.length+1}`;this.draftAreaId="";this.draftWidth="";this.draftHeight="";this.draftFlipX=false;this.draftFlipY=false;this.calA=undefined;this.calB=undefined;this.drawingMode="draw-new";}
 private beginRedraw(){if(this.selectedRoom){this.pendingPoints=[];this.drawingMode="redraw";}}
 private beginAnchor(){if(this.selectedRoom){this.pendingAnchor=undefined;this.drawingMode="anchor";}}
 private cancelDrawing(){this.pendingPoints=[];this.pendingAnchor=undefined;this.drawingMode="idle";}
 private undoPoint(){this.pendingPoints=this.pendingPoints.slice(0,-1);}
 private meters(){const width=Number(this.draftWidth.replace(",",".")),height=Number(this.draftHeight.replace(",","."));return width>0&&height>0?{width,height,flip_x:this.draftFlipX,flip_y:this.draftFlipY,...(this.calA&&this.calB?{position_calibration:{a:this.calA,b:this.calB}}:{})}:undefined;}
 private finishPolygon(){if(this.pendingPoints.length<3||!this.roomConfig)return;if(this.drawingMode==="draw-new"){const name=this.draftRoomName.trim()||`Rum ${this.rooms.length+1}`,id=this.uniqueRoomId(name),center=roomCenter(this.pendingPoints),physical=this.meters();const room:ExplorerRoom={id,name,points:this.pendingPoints,presence_anchor:center,...(this.draftAreaId?{area_id:this.draftAreaId}:{}),...(physical?{physical_meters:physical}:{})};this.selectedRoomId=id;this.emitConfig({...this.roomConfig,rooms:[...this.rooms,room]});}else if(this.selectedRoom){this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,points:this.pendingPoints}:r)});}this.pendingPoints=[];this.drawingMode="idle";}
 private saveMeters(){if(!this.roomConfig||!this.selectedRoom)return;const physical_meters=this.meters();if(!physical_meters)return;this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,physical_meters}:r)});}
 private savePositionCalibration(){if(!this.roomConfig||!this.selectedRoom||!this.calA||!this.calB)return;const meters=this.selectedRoom.physical_meters;if(!meters)return;const physical_meters={...meters,position_calibration:{a:this.calA,b:this.calB}};this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,physical_meters}:r)});this.calibrationMessage="2-punktskalibrering gemt.";}
 private resetPositionCalibration(){if(!this.roomConfig||!this.selectedRoom?.physical_meters)return;const{position_calibration:_,...rest}=this.selectedRoom.physical_meters;this.calA=undefined;this.calB=undefined;this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,physical_meters:rest}:r)});this.calibrationMessage="Positionskalibrering nulstillet.";}
 private removeSelectedRoom(){if(!this.roomConfig||!this.selectedRoom)return;const roomId=this.selectedRoom.id,rooms=this.rooms.filter(r=>r.id!==roomId),presences=(this.roomConfig.presences??[]).map(p=>p.room_id===roomId?{...p,room_id:undefined}:p);this.selectedRoomId="";this.emitConfig({...this.roomConfig,rooms,presences});}
 private finishAnchor(){if(!this.roomConfig||!this.selectedRoom||!this.pendingAnchor)return;const anchor={...this.pendingAnchor};this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,presence_anchor:anchor}:r)});this.pendingAnchor=undefined;this.drawingMode="idle";}
 private renderRoomPolygon(room:ExplorerRoom){if(!room.points.length)return nothing;const pts=room.points.map(([x,y])=>`${x*1000},${y*1000}`).join(" "),selected=room.id===this.selectedRoomId,c=roomCenter(room.points),a=selected&&this.drawingMode==="anchor"&&this.pendingAnchor?this.pendingAnchor:(room.presence_anchor??c);return svg`<g style=${this.drawingMode==="idle"?"pointer-events:auto":"pointer-events:none"} @click=${(e:MouseEvent)=>this.selectRoom(e,room.id)}><polygon points=${pts} fill="var(--primary-color,#03a9f4)" fill-opacity=${selected?".30":".14"} stroke="var(--primary-color,#03a9f4)" stroke-width=${selected?7:4}/><text x=${c.x*1000} y=${c.y*1000} text-anchor="middle" dominant-baseline="middle">${room.name??room.id}</text>${selected?svg`<circle cx=${a.x*1000} cy=${a.y*1000} r="15" class="anchor"/>`:nothing}</g>`;}
 private renderPending(){if(!this.pendingPoints.length)return nothing;const pts=this.pendingPoints.map(([x,y])=>`${x*1000},${y*1000}`).join(" ");return svg`${this.pendingPoints.length>=3?svg`<polygon points=${pts} class="pending-fill"/>`:nothing}<polyline points=${pts} class="pending-line" fill="none"/>${this.pendingPoints.map(([x,y],i)=>svg`<circle cx=${x*1000} cy=${y*1000} r="13" class="pending-point"/><text x=${x*1000} y=${y*1000-22} text-anchor="middle">${i+1}</text>`)}`;}
 private dimensionFields(){return html`<div class="dimensions"><label>Bredde (m)<input inputmode="decimal" placeholder="4,3" .value=${this.draftWidth} @input=${(e:InputEvent)=>this.draftWidth=(e.target as HTMLInputElement).value}></label><label>Længde (m)<input inputmode="decimal" placeholder="5,4" .value=${this.draftHeight} @input=${(e:InputEvent)=>this.draftHeight=(e.target as HTMLInputElement).value}></label><label class="toggle"><input type="checkbox" .checked=${this.draftFlipX} @change=${(e:Event)=>this.draftFlipX=(e.target as HTMLInputElement).checked}> Vend vandret (X)</label><label class="toggle"><input type="checkbox" .checked=${this.draftFlipY} @change=${(e:Event)=>this.draftFlipY=(e.target as HTMLInputElement).checked}> Vend lodret (Y)</label>${this.drawingMode==="idle"&&this.selectedRoom?html`<button class="primary" ?disabled=${!this.meters()} @click=${this.saveMeters}>Gem rumkalibrering</button>`:nothing}</div>`;}
 private positionCalibration(){if(!this.selectedRoom||this.drawingMode!=="idle")return nothing;const presence=this.selectedPresence();return html`<div class="position-cal"><strong>2-punkts positionskalibrering</strong><span>${presence?`Live target: ${presence.name??presence.id}`:"Bind først et room_meters-target til rummet."}</span><div class="cal-status"><span>Punkt A: ${this.calA?"✓ gemt":"ikke gemt"}</span><span>Punkt B: ${this.calB?"✓ gemt":"ikke gemt"}</span></div><div class="buttons"><button ?disabled=${!presence} @click=${()=>this.drawingMode="cal-a"}>Gem punkt A</button><button ?disabled=${!presence} @click=${()=>this.drawingMode="cal-b"}>Gem punkt B</button><button class="primary" ?disabled=${!this.calA||!this.calB} @click=${this.savePositionCalibration}>Gem 2-punktskalibrering</button><button ?disabled=${!this.selectedRoom.physical_meters?.position_calibration&&!this.calA&&!this.calB} @click=${this.resetPositionCalibration}>Nulstil positionskalibrering</button></div>${this.calibrationMessage?html`<small>${this.calibrationMessage}</small>`:nothing}<small>Tryk A/B, stå på referencepunktet, og klik derefter samme sted på plantegningen.</small></div>`;}
 protected renderRoomDrawingEditor():TemplateResult<1>{if(!this.roomConfig)return html``;const image=this.roomConfig.image??this.roomConfig.background??"",preserve=this.roomConfig.fit_mode==="cover"?"xMidYMid slice":"xMidYMid meet";const instruction=this.drawingMode==="cal-a"||this.drawingMode==="cal-b"?`Stå på referencepunkt ${this.drawingMode==="cal-a"?"A":"B"} og klik det samme sted på plantegningen.`:this.drawingMode==="idle"?"Vælg et rum. Kalibrér mål/orientering og derefter to fysiske referencepunkter.":this.drawingMode==="anchor"?"Klik hvor personpunktet skal være.":"Klik rundt langs rummets kant. Mindst 3 punkter.";return html`<section class="drawing-editor"><div class="heading"><div><small>VISUAL POSITION CALIBRATION · v0.33.0</small><h3>Tegn, mål, orientér og finjustér live-positioner</h3></div><b>${this.rooms.length} rum</b></div><div class="instruction">${instruction}</div>${this.drawingMode==="draw-new"?html`<div class="grid"><label>Rumnavn<input .value=${this.draftRoomName} @input=${(e:InputEvent)=>this.draftRoomName=(e.target as HTMLInputElement).value}></label><label>Home Assistant Area<select .value=${this.draftAreaId} @change=${(e:Event)=>this.draftAreaId=(e.target as HTMLSelectElement).value}><option value="">Ikke bundet</option>${this.drawingAreas.map(a=>html`<option value=${a.area_id}>${a.name}</option>`)}</select></label></div>${this.dimensionFields()}`:this.selectedRoom&&this.drawingMode==="idle"?html`<div class="selected"><strong>${this.selectedRoom.name??this.selectedRoom.id}</strong><span>${this.selectedRoom.points.length} punkter · ${this.selectedRoom.physical_meters?.width??"?"} × ${this.selectedRoom.physical_meters?.height??"?"} m</span></div>${this.dimensionFields()}${this.positionCalibration()}`:nothing}${image?html`<div class="map-frame"><svg viewBox="0 0 1000 1000" preserveAspectRatio="none" @click=${this.handleMapClick}><image href=${image} width="1000" height="1000" preserveAspectRatio=${preserve}/>${this.rooms.map(r=>this.renderRoomPolygon(r))}${this.renderPending()}</svg></div>`:nothing}<div class="buttons">${this.drawingMode==="draw-new"||this.drawingMode==="redraw"?html`<button @click=${this.undoPoint}>Fortryd punkt</button><button class="primary" ?disabled=${this.pendingPoints.length<3||(this.drawingMode==="draw-new"&&!this.meters())} @click=${this.finishPolygon}>Gem rum</button><button @click=${this.cancelDrawing}>Annuller</button>`:this.drawingMode==="anchor"||this.drawingMode==="cal-a"||this.drawingMode==="cal-b"?html`<button @click=${this.cancelDrawing}>Annuller</button>`:html`<button class="primary" @click=${this.beginNewRoom}>+ Nyt rum</button><button ?disabled=${!this.selectedRoom} @click=${this.beginRedraw}>Tegn rumkant igen</button><button ?disabled=${!this.selectedRoom} @click=${this.beginAnchor}>Placér personpunkt</button><button class="danger" ?disabled=${!this.selectedRoom} @click=${this.removeSelectedRoom}>Slet valgt rum</button>`}</div></section>`;}
 protected render(){return html`<ha-explorer-card-editor .hass=${this.hass} @config-changed=${this.handleBaseConfigChanged}></ha-explorer-card-editor>${this.renderRoomDrawingEditor()}`;}
 static styles=css`:host{display:block}.drawing-editor{margin-top:18px;display:grid;gap:14px;padding:16px;border:1px solid var(--divider-color);border-radius:14px;background:var(--ha-card-background,var(--card-background-color))}.heading{display:flex;justify-content:space-between;gap:12px}.heading h3{margin:3px 0}.heading small{color:var(--secondary-text-color);font-weight:700;letter-spacing:.08em}.instruction,.selected,.position-cal{padding:10px 12px;border-radius:10px;background:var(--secondary-background-color);color:var(--secondary-text-color)}.position-cal{display:grid;gap:9px}.grid,.dimensions{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;align-items:end}.cal-status{display:flex;gap:18px;flex-wrap:wrap}label{display:grid;gap:5px;font-size:.8rem;color:var(--secondary-text-color)}label.toggle{display:flex;align-items:center;gap:8px;min-height:38px;font-size:.9rem;color:var(--primary-text-color)}label.toggle input{width:auto}input,select{box-sizing:border-box;width:100%;padding:9px;border:1px solid var(--divider-color);border-radius:8px;background:var(--card-background-color);color:var(--primary-text-color)}.map-frame{overflow:hidden;border:1px solid var(--divider-color);border-radius:12px;background:var(--secondary-background-color)}svg{display:block;width:100%;height:min(58vh,620px);cursor:crosshair}text{fill:var(--primary-text-color);font-size:24px;font-weight:700}.pending-fill{fill:var(--primary-color);fill-opacity:.18;stroke:var(--primary-color);stroke-width:5}.pending-line{stroke:var(--primary-color);stroke-width:6}.pending-point,.anchor{fill:var(--primary-color);stroke:white;stroke-width:4}.buttons{display:flex;flex-wrap:wrap;gap:8px}button{padding:9px 13px;border:1px solid var(--divider-color);border-radius:9px;background:var(--secondary-background-color);color:var(--primary-text-color);cursor:pointer}button.primary{background:var(--primary-color);color:var(--text-primary-color,#fff);border-color:var(--primary-color)}button.danger{background:var(--error-color,#db4437);color:#fff;border-color:var(--error-color,#db4437)}button:disabled{opacity:.45;cursor:not-allowed}.selected{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}`;
}
