import { css } from "lit";
import { customElement } from "lit/decorators.js";
import { ExplorerZonesCanvas } from "./explorer-zones-canvas";
import type { ExplorerPresence, PresenceObjectType } from "../models/config";
import { resolveRoute } from "../utils/route-resolver";
import { VIEWBOX_SIZE } from "../utils/viewport";

interface PolishPosition { x:number; y:number; }
interface PolishOffset { x:number; y:number; groupSize:number; }
const POLISH_SVG_NAMESPACE="http://www.w3.org/2000/svg",POLISH_TRAIL_LIFETIME_MS=4200,POLISH_MOVEMENT_DURATION_MS=900;
const POLISH_OVERLAP_DISTANCE=54;
const POLISH_TYPE_LABELS:Record<PresenceObjectType,string>={person:"Person",pet:"Kæledyr",robot:"Robot",vehicle:"Køretøj",object:"Objekt"};
const POLISH_TYPE_HUES:Record<PresenceObjectType,number[]>={person:[202,344,42,158,274,18],pet:[28,112,326,52,178,286],robot:[188,218,264,164,204,238],vehicle:[12,210,38,330,186,262],object:[272,44,154,320,196,22]};
function polishHash(value:string):number{let hash=2166136261;for(let i=0;i<value.length;i+=1){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619);}return hash>>>0;}
function polishClamp(value:number,min:number,max:number):number{return Math.min(max,Math.max(min,value));}
@customElement("explorer-presence-polish-canvas")
export class ExplorerPresencePolishCanvas extends ExplorerZonesCanvas{
 private readonly polishPreviousPositions=new Map<string,PolishPosition>();private readonly polishPreviousRooms=new Map<string,string|undefined>();
 protected override updated(changed:Map<PropertyKey,unknown>):void{super.updated(changed);if(changed.has("presences")||changed.has("theme"))this.polishSyncPresenceVisuals();if(changed.has("presences"))this.polishSyncTrails();}
 private polishPresenceColor(p:ExplorerPresence):string{const c=p.color?.trim();if(c)return c;const t=p.type??"person",h=POLISH_TYPE_HUES[t][polishHash(p.id)%POLISH_TYPE_HUES[t].length];return this.theme==="enchanted_antique"?`hsl(${h} 34% 38%)`:`hsl(${h} 62% 47%)`;}
 private polishTrailColor(p:ExplorerPresence):string{return p.trail_color?.trim()||this.polishPresenceColor(p);}
 private polishTrailDuration(p:ExplorerPresence):number{const seconds=p.trail_duration;if(!Number.isFinite(seconds))return POLISH_TRAIL_LIFETIME_MS;return Math.round(polishClamp(seconds as number,1,60)*1000);}
 private polishBasePosition(p:ExplorerPresence):PolishPosition{return{x:(p.x??.5)*VIEWBOX_SIZE,y:(p.y??.5)*VIEWBOX_SIZE};}
 private polishOffsets(presences:ExplorerPresence[]):Map<string,PolishOffset>{const offsets=new Map<string,PolishOffset>();presences.forEach(p=>offsets.set(p.id,{x:0,y:0,groupSize:1}));const remaining=new Set(presences.map(p=>p.id));const byId=new Map(presences.map(p=>[p.id,p]));while(remaining.size){const seedId=remaining.values().next().value as string,seed=byId.get(seedId);remaining.delete(seedId);if(!seed)continue;const cluster=[seed],queue=[seed];while(queue.length){const current=queue.shift()!;const cp=this.polishBasePosition(current);for(const id of [...remaining]){const candidate=byId.get(id);if(!candidate)continue;const pp=this.polishBasePosition(candidate);if(Math.hypot(cp.x-pp.x,cp.y-pp.y)<=POLISH_OVERLAP_DISTANCE){remaining.delete(id);cluster.push(candidate);queue.push(candidate);}}}if(cluster.length<2)continue;const ordered=[...cluster].sort((a,b)=>a.id.localeCompare(b.id));const radius=Math.min(52,24+ordered.length*4);ordered.forEach((p,index)=>{const base=this.polishBasePosition(p),angle=ordered.length===2?(index===0?Math.PI:0):-Math.PI/2+Math.PI*2*index/ordered.length,targetX=polishClamp(base.x+Math.cos(angle)*radius,38,VIEWBOX_SIZE-38),targetY=polishClamp(base.y+Math.sin(angle)*radius,38,VIEWBOX_SIZE-64);offsets.set(p.id,{x:targetX-base.x,y:targetY-base.y,groupSize:ordered.length});});}return offsets;}
 private polishCreateSvg<K extends keyof SVGElementTagNameMap>(tag:K):SVGElementTagNameMap[K]{return document.createElementNS(POLISH_SVG_NAMESPACE,tag);}
 private polishSetAttributes(el:Element,attrs:Record<string,string>):void{Object.entries(attrs).forEach(([n,v])=>el.setAttribute(n,v));}
 private polishAppendTypeBadge(w:SVGGElement,p:ExplorerPresence,color:string):void{if(w.querySelector(":scope > g.presence-type-badge"))return;const type=p.type??"person",badge=this.polishCreateSvg("g");badge.setAttribute("class",`presence-type-badge badge-${type}`);badge.setAttribute("transform","translate(21 -21)");badge.setAttribute("pointer-events","none");const bg=this.polishCreateSvg("circle");this.polishSetAttributes(bg,{r:"9.5",fill:"var(--card-background-color, #ffffff)","fill-opacity":".94",stroke:color,"stroke-width":"2.5","vector-effect":"non-scaling-stroke"});badge.appendChild(bg);if(type==="person"){const h=this.polishCreateSvg("circle");this.polishSetAttributes(h,{cx:"0",cy:"-2.8",r:"2.5",fill:color});const b=this.polishCreateSvg("path");this.polishSetAttributes(b,{d:"M -4 5 Q -3 0 0 0 Q 3 0 4 5 Z",fill:color});badge.append(h,b);}else if(type==="pet"){const pad=this.polishCreateSvg("ellipse");this.polishSetAttributes(pad,{cx:"0",cy:"2",rx:"3.4",ry:"3",fill:color});badge.appendChild(pad);[[-4,-2],[-1.5,-4.6],[1.5,-4.6],[4,-2]].forEach(([cx,cy])=>{const toe=this.polishCreateSvg("circle");this.polishSetAttributes(toe,{cx:String(cx),cy:String(cy),r:"1.5",fill:color});badge.appendChild(toe);});}else if(type==="robot"){const b=this.polishCreateSvg("rect");this.polishSetAttributes(b,{x:"-5",y:"-4",width:"10",height:"8",rx:"2",fill:color});badge.appendChild(b);[-2.2,2.2].forEach(cx=>{const e=this.polishCreateSvg("circle");this.polishSetAttributes(e,{cx:String(cx),cy:"-1",r:"1",fill:"var(--card-background-color, #ffffff)"});badge.appendChild(e);});}else if(type==="vehicle"){const b=this.polishCreateSvg("rect");this.polishSetAttributes(b,{x:"-5.5",y:"-2.5",width:"11",height:"5",rx:"1.5",fill:color});badge.appendChild(b);}else{const d=this.polishCreateSvg("path");this.polishSetAttributes(d,{d:"M 0 -6 L 5 0 L 0 6 L -5 0 Z",fill:color});badge.appendChild(d);}w.appendChild(badge);}
 private polishSyncPresenceVisuals():void{const visible=this.presences.filter(p=>p.visible!==false),elements=Array.from(this.renderRoot.querySelectorAll<SVGGElement>("g.presence")),offsets=this.polishOffsets(visible);visible.forEach((p,index)=>{const el=elements[index];if(!el)return;const type=p.type??"person",color=this.polishPresenceColor(p),offset=offsets.get(p.id)??{x:0,y:0,groupSize:1};el.setAttribute("data-presence-id",p.id);el.setAttribute("data-presence-type",type);el.classList.add("presence-polished",`presence-${type}`);let w=el.querySelector<SVGGElement>(":scope > g.presence-visual-offset");if(!w){w=this.polishCreateSvg("g");w.setAttribute("class","presence-visual-offset");Array.from(el.children).filter(c=>c.localName.toLowerCase()!=="animatetransform").forEach(c=>w?.appendChild(c));el.insertBefore(w,el.firstChild);}w.setAttribute("transform",`translate(${offset.x} ${offset.y})`);w.querySelector<SVGElement>(".presence-marker")?.setAttribute("fill",color);w.querySelector<SVGElement>(".presence-avatar-background")?.setAttribute("fill",color);w.querySelector<SVGElement>(".presence-border")?.setAttribute("stroke",color);this.polishAppendTypeBadge(w,p,color);el.querySelector(":scope > title")?.remove();const title=this.polishCreateSvg("title"),groupText=offset.groupSize>1?` · ${offset.groupSize} markører overlapper`:"";title.textContent=`${p.name??p.id} · ${POLISH_TYPE_LABELS[type]}${groupText}`;el.appendChild(title);});}
 private polishRouteConfig(){return{type:"custom:ha-explorer-card",rooms:this.rooms,route_nodes:this.routeNodes,route_graph_edges:this.routeGraphEdges,routes:this.routes};}
 private polishMovementPath(from:PolishPosition,to:PolishPosition,fromRoom?:string,toRoom?:string):PolishPosition[]{if(!fromRoom||!toRoom||fromRoom===toRoom)return[from,to];const r=resolveRoute(this.polishRouteConfig(),fromRoom,toRoom,id=>this.hass?.states[id]?.state);if(!r)return[from,to];return[from,...r.hops.slice(1,-1).map(h=>({x:h.point[0]*VIEWBOX_SIZE,y:h.point[1]*VIEWBOX_SIZE})),to];}
 private polishEnsureTrailLayer():SVGGElement|undefined{const scene=this.renderRoot.querySelector<SVGGElement>("g.scene");if(!scene)return;let layer=scene.querySelector<SVGGElement>(":scope > g.presence-trails-scene");if(layer)return layer;layer=this.polishCreateSvg("g");layer.setAttribute("class","presence-trails-scene");layer.setAttribute("aria-label","Person- og objektspor");layer.setAttribute("pointer-events","none");scene.insertBefore(layer,scene.querySelector<SVGGElement>(":scope > g.presences-scene")??null);return layer;}
 private polishTrailSpacing(type:PresenceObjectType):number{return type==="pet"?46:type==="robot"?42:type==="vehicle"?54:type==="object"?62:58;}
 private polishAppendTrailShape(mark:SVGGElement,type:PresenceObjectType,color:string):void{if(type==="person"){const sole=this.polishCreateSvg("ellipse"),heel=this.polishCreateSvg("ellipse");this.polishSetAttributes(sole,{cx:"0",cy:"-5",rx:"5.5",ry:"11",fill:color});this.polishSetAttributes(heel,{cx:"0",cy:"8",rx:"4",ry:"5",fill:color});mark.append(sole,heel);return;}if(type==="pet"){const pad=this.polishCreateSvg("ellipse");this.polishSetAttributes(pad,{cx:"0",cy:"2",rx:"5",ry:"6",fill:color});mark.appendChild(pad);return;}if(type==="robot"){[-7,3].forEach(x=>{const t=this.polishCreateSvg("rect");this.polishSetAttributes(t,{x:String(x),y:"-8",width:"4",height:"16",rx:"1.4",fill:color});mark.appendChild(t);});return;}if(type==="vehicle"){[-7,4].forEach(x=>{const t=this.polishCreateSvg("rect");this.polishSetAttributes(t,{x:String(x),y:"-11",width:"3",height:"22",rx:"1",fill:color});mark.appendChild(t);});return;}const d=this.polishCreateSvg("path");this.polishSetAttributes(d,{d:"M 0 -7 L 6 0 L 0 7 L -6 0 Z",fill:color});mark.appendChild(d);}
 private polishCreateTrail(path:PolishPosition[],p:ExplorerPresence):void{if(p.trail_visible===false)return;const layer=this.polishEnsureTrailLayer();if(!layer||path.length<2)return;const type=p.type??"person",color=this.polishTrailColor(p),lifetime=this.polishTrailDuration(p),segments=path.slice(1).map((point,index)=>{const start=path[index];return{start,end:point,length:Math.hypot(point.x-start.x,point.y-start.y)};}),total=segments.reduce((s,x)=>s+x.length,0),spacing=this.polishTrailSpacing(type);if(total<spacing)return;const count=Math.min(24,Math.max(3,Math.floor(total/spacing)));for(let index=0;index<count;index+=1){const progress=(index+1)/(count+1),target=total*progress;let traversed=0,segment=segments[segments.length-1];for(const c of segments){if(traversed+c.length>=target){segment=c;break;}traversed+=c.length;}const local=segment.length>0?(target-traversed)/segment.length:0,dx=segment.end.x-segment.start.x,dy=segment.end.y-segment.start.y,side=index%2===0?-1:1,alternating=type==="person"?8:type==="pet"?6:0,px=segment.length>0?-dy/segment.length:0,py=segment.length>0?dx/segment.length:0,x=segment.start.x+dx*local+px*alternating*side,y=segment.start.y+dy*local+py*alternating*side,angle=Math.atan2(dy,dx)*180/Math.PI+90,delay=Math.round(progress*POLISH_MOVEMENT_DURATION_MS),mark=this.polishCreateSvg("g");mark.setAttribute("class",`trail-mark trail-${type}`);mark.setAttribute("data-presence-id",p.id);mark.setAttribute("transform",`translate(${x} ${y}) rotate(${angle+(alternating?side*7:0)})`);mark.setAttribute("opacity","0");this.polishAppendTrailShape(mark,type,color);const fade=this.polishCreateSvg("animate");this.polishSetAttributes(fade,{attributeName:"opacity",values:"0;0.78;0.54;0",keyTimes:"0;0.08;0.58;1",begin:"indefinite",dur:`${lifetime}ms`,fill:"freeze"});mark.appendChild(fade);layer.appendChild(mark);window.setTimeout(()=>{if(mark.isConnected)(fade as SVGAnimationElement).beginElement();},delay);window.setTimeout(()=>mark.remove(),delay+lifetime+120);}}
 private polishSyncTrails():void{const visible=this.presences.filter(p=>p.visible!==false),reduce=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches??false,currentIds=new Set<string>();visible.forEach(p=>{const current=this.polishBasePosition(p),previous=this.polishPreviousPositions.get(p.id),previousRoom=this.polishPreviousRooms.get(p.id),currentRoom=p.room_id;currentIds.add(p.id);if(!reduce&&previous&&(Math.abs(previous.x-current.x)>.01||Math.abs(previous.y-current.y)>.01))this.polishCreateTrail(this.polishMovementPath(previous,current,previousRoom,currentRoom),p);this.polishPreviousPositions.set(p.id,current);this.polishPreviousRooms.set(p.id,currentRoom);});for(const id of this.polishPreviousPositions.keys())if(!currentIds.has(id)){this.polishPreviousPositions.delete(id);this.polishPreviousRooms.delete(id);}}
 static override styles=css`${ExplorerZonesCanvas.styles}.footsteps-scene{display:none}.presence-visual-offset{transition:transform 220ms ease}.presence-type-badge{filter:drop-shadow(0 1px 2px rgba(0,0,0,.22))}.presence-trails-scene .trail-mark{filter:drop-shadow(0 0 1.2px rgba(0,0,0,.20))}:host([map-theme="enchanted_antique"]) .presence-type-badge{filter:sepia(.35) drop-shadow(0 1px 1px rgba(67,40,22,.28))}:host([map-theme="enchanted_antique"]) .presence-trails-scene .trail-mark{mix-blend-mode:multiply;filter:sepia(.28) saturate(.78) drop-shadow(0 0 1px rgba(67,40,22,.28))}:host([map-theme="enchanted_antique"]) .presence-border{stroke-width:4.5px!important}@media(prefers-reduced-motion:reduce){.presence-visual-offset{transition:none}}`;
}
