import { customElement } from "lit/decorators.js";
import { ExplorerAnimatedCanvas } from "./explorer-animated-canvas";
import type { ExplorerRoom, RoomReactionKind } from "../models/config";
import { evaluateRoomReactions, roomReactionPosition, type RoomReactionStatus } from "../utils/room-reactions";
import { VIEWBOX_SIZE } from "../utils/viewport";
const SVG_NAMESPACE="http://www.w3.org/2000/svg";
@customElement("explorer-living-canvas")
export class ExplorerLivingCanvas extends ExplorerAnimatedCanvas{
 protected override updated(changed:Map<PropertyKey,unknown>):void{super.updated(changed);this.syncRoomReactionOverlay();}
 private entityState(entityId:string){const entity=this.hass?.states[entityId];if(!entity)return undefined;return{state:entity.state,attributes:entity.attributes};}
 private appendTitle(parent:SVGElement,text:string):void{const title=document.createElementNS(SVG_NAMESPACE,"title");title.textContent=text;parent.appendChild(title);}
 private pointColor(kind:RoomReactionKind):string{if(kind==="light")return"var(--explorer-room-light-color, #f6bd60)";if(kind==="motion")return"var(--explorer-room-motion-color, var(--primary-color, #03a9f4))";if(kind==="media")return"var(--explorer-room-media-color, var(--accent-color, #7e57c2))";if(kind==="opening")return"var(--explorer-room-opening-color, var(--warning-color, #ff9800))";if(kind==="fireplace")return"var(--explorer-room-fireplace-color, #c46b2d)";return"var(--explorer-room-temperature-neutral, #4f9b78)";}
 private appendPointBackdrop(group:SVGGElement,color:string,active:boolean,radius=11):SVGCircleElement{const circle=document.createElementNS(SVG_NAMESPACE,"circle");circle.setAttribute("r",String(radius));circle.setAttribute("fill","var(--card-background-color, #ffffff)");circle.setAttribute("fill-opacity",active?".94":".78");circle.setAttribute("stroke",color);circle.setAttribute("stroke-width",active?"3":"2");circle.setAttribute("stroke-opacity",active?".95":".42");circle.setAttribute("vector-effect","non-scaling-stroke");group.appendChild(circle);return circle;}
 private appendLightPoint(group:SVGGElement,status:RoomReactionStatus,reduceMotion:boolean):void{const color=this.pointColor("light");if(status.active){group.setAttribute("data-magical-light","active");const intensity=Math.max(.18,Math.min(1,status.intensity));const layers=[[74,.025],[52,.055],[34,.12]] as const;layers.forEach(([radius,opacity],index)=>{const glow=document.createElementNS(SVG_NAMESPACE,"circle");glow.setAttribute("class",`magical-light-glow glow-${index+1}`);glow.setAttribute("r",String(radius*(.82+intensity*.34)));glow.setAttribute("fill",color);glow.setAttribute("fill-opacity",String(opacity+intensity*opacity*1.8));glow.setAttribute("stroke","none");group.appendChild(glow);if(!reduceMotion&&index===1){const pulse=document.createElementNS(SVG_NAMESPACE,"animate");pulse.setAttribute("attributeName","fill-opacity");pulse.setAttribute("values",`${opacity+intensity*.07};${opacity+intensity*.13};${opacity+intensity*.07}`);pulse.setAttribute("dur","4.8s");pulse.setAttribute("repeatCount","indefinite");glow.appendChild(pulse);}});const halo=document.createElementNS(SVG_NAMESPACE,"circle");const radius=24+intensity*24;halo.setAttribute("class","light-halo");halo.setAttribute("r",String(radius));halo.setAttribute("fill",color);halo.setAttribute("fill-opacity",String(.08+intensity*.18));halo.setAttribute("stroke",color);halo.setAttribute("stroke-width","2");halo.setAttribute("stroke-opacity",String(.10+intensity*.18));halo.setAttribute("vector-effect","non-scaling-stroke");group.appendChild(halo);if(!reduceMotion){const breathe=document.createElementNS(SVG_NAMESPACE,"animate");breathe.setAttribute("attributeName","r");breathe.setAttribute("values",`${radius*.94};${radius*1.06};${radius*.94}`);breathe.setAttribute("dur","4.2s");breathe.setAttribute("repeatCount","indefinite");halo.appendChild(breathe);}}
 this.appendPointBackdrop(group,color,status.active,11);const glyph=document.createElementNS(SVG_NAMESPACE,"text");glyph.setAttribute("class","light-glyph");glyph.setAttribute("text-anchor","middle");glyph.setAttribute("dominant-baseline","central");glyph.setAttribute("font-size","15");glyph.setAttribute("font-weight","900");glyph.setAttribute("fill",color);glyph.setAttribute("opacity",status.active?"1":".48");glyph.textContent="✦";group.appendChild(glyph);}
 private appendMotionPoint(group:SVGGElement,status:RoomReactionStatus,reduceMotion:boolean):void{const color=this.pointColor("motion");this.appendPointBackdrop(group,color,status.active,10);const dot=document.createElementNS(SVG_NAMESPACE,"circle");dot.setAttribute("r",status.active?"4.5":"3.5");dot.setAttribute("fill",color);dot.setAttribute("opacity",status.active?"1":".42");group.appendChild(dot);if(!status.active)return;const pulse=document.createElementNS(SVG_NAMESPACE,"circle");pulse.setAttribute("r","15");pulse.setAttribute("fill","none");pulse.setAttribute("stroke",color);pulse.setAttribute("stroke-width","3");pulse.setAttribute("stroke-opacity",".78");pulse.setAttribute("vector-effect","non-scaling-stroke");group.insertBefore(pulse,group.firstChild);if(!reduceMotion){const radius=document.createElementNS(SVG_NAMESPACE,"animate");radius.setAttribute("attributeName","r");radius.setAttribute("values","13;31;13");radius.setAttribute("dur","1.8s");radius.setAttribute("repeatCount","indefinite");pulse.appendChild(radius);}}
 private appendMediaPoint(group:SVGGElement,status:RoomReactionStatus):void{const color=this.pointColor("media");if(status.active){const halo=document.createElementNS(SVG_NAMESPACE,"circle");halo.setAttribute("r","25");halo.setAttribute("fill",color);halo.setAttribute("fill-opacity",".12");group.appendChild(halo);}const screen=document.createElementNS(SVG_NAMESPACE,"rect");screen.setAttribute("x","-16");screen.setAttribute("y","-11");screen.setAttribute("width","32");screen.setAttribute("height","22");screen.setAttribute("rx","4");screen.setAttribute("fill","var(--card-background-color, #ffffff)");screen.setAttribute("fill-opacity",status.active?".94":".78");screen.setAttribute("stroke",color);screen.setAttribute("stroke-width",status.active?"3":"2");screen.setAttribute("stroke-opacity",status.active?".95":".42");group.appendChild(screen);const play=document.createElementNS(SVG_NAMESPACE,"path");play.setAttribute("d","M -4 -6 L 7 0 L -4 6 Z");play.setAttribute("fill",color);play.setAttribute("opacity",status.active?"1":".40");group.appendChild(play);}
 private appendOpeningPoint(group:SVGGElement,status:RoomReactionStatus):void{const color=this.pointColor("opening");this.appendPointBackdrop(group,color,status.active,11);const glyph=document.createElementNS(SVG_NAMESPACE,"text");glyph.setAttribute("text-anchor","middle");glyph.setAttribute("dominant-baseline","central");glyph.setAttribute("font-size",status.active?"18":"15");glyph.setAttribute("font-weight","900");glyph.setAttribute("fill",color);glyph.setAttribute("opacity",status.active?"1":".42");glyph.textContent=status.active?"↗":"━";group.appendChild(glyph);}
 private appendFireplacePoint(group:SVGGElement,status:RoomReactionStatus,reduceMotion:boolean):void{const color=this.pointColor("fireplace"),intensity=Math.max(.2,Math.min(1,status.intensity||1)),configuredRadius=status.reaction.radius,baseRadius=Number.isFinite(configuredRadius)?Math.max(26,Math.min(160,(configuredRadius as number)*VIEWBOX_SIZE)):72;if(status.active){group.setAttribute("data-fireplace","active");const glow1=document.createElementNS(SVG_NAMESPACE,"circle");glow1.setAttribute("class","fireplace-glow fireplace-glow-outer");glow1.setAttribute("r",String(baseRadius));glow1.setAttribute("fill",color);glow1.setAttribute("fill-opacity",String(.07+.11*intensity));group.appendChild(glow1);const glow2=document.createElementNS(SVG_NAMESPACE,"circle");glow2.setAttribute("class","fireplace-glow fireplace-glow-inner");glow2.setAttribute("r",String(baseRadius*.56));glow2.setAttribute("fill","var(--explorer-room-fireplace-hot, #e7a253)");glow2.setAttribute("fill-opacity",String(.12+.17*intensity));group.appendChild(glow2);if(!reduceMotion){const flicker=document.createElementNS(SVG_NAMESPACE,"animate");flicker.setAttribute("attributeName","fill-opacity");flicker.setAttribute("values",`${.1+.12*intensity};${.2+.18*intensity};${.12+.1*intensity};${.24+.16*intensity};${.1+.12*intensity}`);flicker.setAttribute("dur","2.1s");flicker.setAttribute("repeatCount","indefinite");glow2.appendChild(flicker);const breathe=document.createElementNS(SVG_NAMESPACE,"animate");breathe.setAttribute("attributeName","r");breathe.setAttribute("values",`${baseRadius*.93};${baseRadius*1.05};${baseRadius*.97};${baseRadius*.93}`);breathe.setAttribute("dur","3.6s");breathe.setAttribute("repeatCount","indefinite");glow1.appendChild(breathe);}}
 this.appendPointBackdrop(group,color,status.active,12);const flame=document.createElementNS(SVG_NAMESPACE,"path");flame.setAttribute("d","M 0 9 C -8 4 -7 -4 -1 -10 C -1 -5 3 -4 4 -10 C 11 -2 10 5 4 9 C 3 5 1 2 0 -1 C -3 3 -3 6 0 9 Z");flame.setAttribute("fill",color);flame.setAttribute("opacity",status.active?"1":".42");group.appendChild(flame);}
 private temperatureColor(status:RoomReactionStatus):string{if(status.numericValue===undefined)return"var(--secondary-text-color, #777777)";const unit=status.unit?.toLowerCase()??"",celsius=unit.includes("f")?(status.numericValue-32)*(5/9):status.numericValue;if(celsius<18)return"var(--explorer-room-temperature-cold, #4f87c5)";if(celsius<=22)return"var(--explorer-room-temperature-neutral, #4f9b78)";if(celsius<=25)return"var(--explorer-room-temperature-warm, #d69b39)";return"var(--explorer-room-temperature-hot, #c65b45)";}
 private formatTemperature(status:RoomReactionStatus):string{if(status.numericValue===undefined)return"--";const value=new Intl.NumberFormat("da-DK",{maximumFractionDigits:1}).format(status.numericValue);return status.unit?`${value} ${status.unit}`:`${value}°`;}
 private appendTemperaturePoint(group:SVGGElement,status:RoomReactionStatus):void{const color=this.temperatureColor(status),textValue=this.formatTemperature(status),width=Math.max(58,24+textValue.length*8.2),pill=document.createElementNS(SVG_NAMESPACE,"rect");pill.setAttribute("x",String(-width/2));pill.setAttribute("y","-15");pill.setAttribute("width",String(width));pill.setAttribute("height","30");pill.setAttribute("rx","15");pill.setAttribute("fill","var(--card-background-color, #ffffff)");pill.setAttribute("fill-opacity",status.active?".94":".78");pill.setAttribute("stroke",color);pill.setAttribute("stroke-width","2.5");group.appendChild(pill);const value=document.createElementNS(SVG_NAMESPACE,"text");value.setAttribute("text-anchor","middle");value.setAttribute("dominant-baseline","central");value.setAttribute("font-size","14");value.setAttribute("font-weight","800");value.setAttribute("fill",color);value.textContent=textValue;group.appendChild(value);}
 private appendReactionPoint(layer:SVGGElement,room:ExplorerRoom,status:RoomReactionStatus,reduceMotion:boolean):void{const position=roomReactionPosition(room,status.reaction),group=document.createElementNS(SVG_NAMESPACE,"g");group.setAttribute("class",`room-reaction-point ${status.reaction.kind} ${status.active?"active":"inactive"}`);group.setAttribute("data-reaction-kind",status.reaction.kind);group.setAttribute("transform",`translate(${position.x*VIEWBOX_SIZE} ${position.y*VIEWBOX_SIZE})`);if(status.reaction.kind==="light")this.appendLightPoint(group,status,reduceMotion);else if(status.reaction.kind==="motion")this.appendMotionPoint(group,status,reduceMotion);else if(status.reaction.kind==="media")this.appendMediaPoint(group,status);else if(status.reaction.kind==="opening")this.appendOpeningPoint(group,status);else if(status.reaction.kind==="fireplace")this.appendFireplacePoint(group,status,reduceMotion);else this.appendTemperaturePoint(group,status);const stateText=status.reaction.kind==="temperature"?this.formatTemperature(status):status.currentState??"ukendt";this.appendTitle(group,`${room.name??room.id} · ${status.reaction.entity} · ${stateText}`);layer.appendChild(group);}
 private syncRoomReactionOverlay():void{const scene=this.renderRoot.querySelector<SVGGElement>("g.scene");if(!scene)return;scene.querySelector<SVGGElement>(":scope > g.room-reactions-scene")?.remove();const entries=this.rooms.flatMap(room=>evaluateRoomReactions(room,entityId=>this.entityState(entityId)).map(status=>({room,status})));if(!entries.length)return;const reduceMotion=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches??false,layer=document.createElementNS(SVG_NAMESPACE,"g");layer.setAttribute("class","room-reactions-scene");layer.setAttribute("aria-label","Home Assistant entity-punkter");layer.setAttribute("pointer-events","none");entries.forEach(({room,status})=>this.appendReactionPoint(layer,room,status,reduceMotion));const routeLayer=scene.querySelector<SVGGElement>(":scope > g.route-status-scene"),footstepsLayer=scene.querySelector<SVGGElement>(":scope > g.footsteps-scene"),presencesLayer=scene.querySelector<SVGGElement>(":scope > g.presences-scene");scene.insertBefore(layer,routeLayer??footstepsLayer??presencesLayer??null);}
}
