import { css } from "lit";
import { customElement, property } from "lit/decorators.js";
import { ExplorerZonesCanvas } from "./explorer-zones-canvas";
import type { ExplorerMovementHistoryConfig, ExplorerPresence, PresenceObjectType } from "../models/config";
import { resolveRoute } from "../utils/route-resolver";
import { VIEWBOX_SIZE } from "../utils/viewport";

interface PolishPosition { x:number; y:number; }
interface PolishOffset { x:number; y:number; groupSize:number; }
interface MovementHistorySample extends PolishPosition { roomId?:string; at:number; }
const POLISH_SVG_NAMESPACE="http://www.w3.org/2000/svg",POLISH_TRAIL_LIFETIME_MS=4200,POLISH_MOVEMENT_DURATION_MS=900;
const POLISH_OVERLAP_DISTANCE=54;
const POLISH_TYPE_LABELS:Record<PresenceObjectType,string>={person:"Person",pet:"Kæledyr",robot:"Robot",vehicle:"Køretøj",object:"Objekt"};
const POLISH_TYPE_HUES:Record<PresenceObjectType,number[]>={person:[202,344,42,158,274,18],pet:[28,112,326,52,178,286],robot:[188,218,264,164,204,238],vehicle:[12,210,38,330,186,262],object:[272,44,154,320,196,22]};
const PERSON_TRAIL_SPACING=[58,64,54,61,56,66] as const;
const PERSON_TRAIL_LATERAL=[8,6,10,7,9,5] as const;
const PERSON_TRAIL_WOBBLE=[7,4,10,6,8,3] as const;
function polishHash(value:string):number{let hash=2166136261;for(let i=0;i<value.length;i+=1){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619);}return hash>>>0;}
function polishClamp(value:number,min:number,max:number):number{return Math.min(max,Math.max(min,value));}
@customElement("explorer-presence-polish-canvas")
export class ExplorerPresencePolishCanvas extends ExplorerZonesCanvas{
 @property({attribute:false}) public movementHistory:ExplorerMovementHistoryConfig={};
 private readonly polishPreviousPositions=new Map<string,PolishPosition>();private readonly polishPreviousRooms=new Map<string,string|undefined>();
 private readonly movementHistorySamples=new Map<string,MovementHistorySample[]>();private movementHistoryTimer?:number;
 protected override updated(changed:Map<PropertyKey,unknown>):void{super.updated(changed);if(changed.has("presences")||changed.has("theme"))this.polishSyncPresenceVisuals();if(changed.has("presences"))this.polishSyncTrails();if(changed.has("presences")||changed.has("movementHistory")||changed.has("rooms")||changed.has("theme"))this.polishSyncMovementHistory();}
 disconnectedCallback():void{super.disconnectedCallback();if(this.movementHistoryTimer!==undefined)window.clearTimeout(this.movementHistoryTimer);}
 private polishPresenceColor(p:ExplorerPresence):string{const c=p.color?.trim();if(c)return c;const t=p.type??"person",h=POLISH_TYPE_HUES[t][polishHash(p.id)%POLISH_TYPE_HUES[t].length];return this.theme==="enchanted_antique"?`hsl(${h} 34% 38%)`:`hsl(${h} 62% 47%)`;}
 private polishTrailColor(p:ExplorerPresence):string{return p.trail_color?.trim()||this.polishPresenceColor(p);}
 private polishTrailDuration(p:ExplorerPresence):number{const seconds=p.trail_duration;if(!Number.isFinite(seconds))return POLISH_TRAIL_LIFETIME_MS;return Math.round(polishClamp(seconds as number,1,60)*1000);}
 private polishBasePosition(p:ExplorerPresence):PolishPosition{return{x:(p.x??.5)*VIEWBOX_SIZE,y:(p.y??.5)*VIEWBOX_SIZE};}
 private polishPersonTrailVariant(p:ExplorerPresence):number{return polishHash(p.id)%PERSON_TRAIL_SPACING.length;}
 private polishOffsets(presences:ExplorerPresence[]):Map<string,PolishOffset>{const offsets=new Map<string,PolishOffset>();presences.forEach(p=>offsets.set(p.id,{x:0,y:0,groupSize:1}));const remaining=new Set(presences.map(p=>p.id));const byId=new Map(presences.map(p=>[p.id,p]));while(remaining.size){const seedId=remaining.values().next().value as string,seed=byId.get(seedId);remaining.delete(seedId);if(!seed)continue;const cluster=[seed],queue=[seed];while(queue.length){const current=queue.shift()!;const cp=this.polishBasePosition(current);for(const id of [...remaining]){const candidate=byId.get(id);if(!candidate)continue;const pp=this.polishBasePosition(candidate);if(Math.hypot(cp.x-pp.x,cp.y-pp.y)<=POLISH_OVERLAP_DISTANCE){remaining.delete(id);cluster.push(candidate);queue.push(candidate);}}}if(cluster.length<2)continue;const ordered=[...cluster].sort((a,b)=>a.id.localeCompare(b.id));const radius=Math.min(52,24+ordered.length*4);ordered.forEach((p,index)=>{const base=this.polishBasePosition(p),angle=ordered.length===2?(index===0?Math.PI:0):-Math.PI/2+Math.PI*2*index/ordered.length,targetX=polishClamp(base.x+Math.cos(angle)*radius,38,VIEWBOX_SIZE-38),targetY=polishClamp(base.y+Math.sin(angle)*radius,38,VIEWBOX_SIZE-64);offsets.set(p.id,{x:targetX-base.x,y:targetY-base.y,groupSize:ordered.length});});}return offsets;}
 private polishCreateSvg<K extends keyof SVGElementTagNameMap>(tag:K):SVGElementTagNameMap[K]{return document.createElementNS(POLISH_SVG_NAMESPACE,tag);}
 private polishSetAttributes(el:Element,attrs:Record<string,string>):void{Object.entries(attrs).forEach(([n,v])=>el.setAttribute(n,v));}
 private polishAppendTypeBadge(w:SVGGElement,p:ExplorerPresence,color:string):void{if(w.querySelector(":scope > g.presence-type-badge"))return;const type=p.type??"person",badge=this.polishCreateSvg("g");badge.setAttribute("class",`presence-type-badge badge-${type}`);badge.setAttribute("transform","translate(21 -21)");badge.setAttribute("pointer-events","none");const bg=this.polishCreateSvg("circle");this.polishSetAttributes(bg,{r:"9.5",fill:"var(--card-background-color, #ffffff)","fill-opacity":".94",stroke:color,"stroke-width":"2.5","vector-effect":"non-scaling-stroke"});badge.appendChild(bg);if(type==="person"){const h=this.polishCreateSvg("circle");this.polishSetAttributes(h,{cx:"0",cy:"-2.8",r:"2.5",fill:color});const b=this.polishCreateSvg("path");this.polishSetAttributes(b,{d:"M -4 5 Q -3 0 0 0 Q 3 0 4 5 Z",fill:color});badge.append(h,b);}else if(type==="pet"){const pad=this.polishCreateSvg("ellipse");this.polishSetAttributes(pad,{cx:"0",cy:"2",rx:"3.4",ry:"3",fill:color});badge.appendChild(pad);[[-4,-2],[-1.5,-4.6],[1.5,-4.6],[4,-2]].forEach(([cx,cy])=>{const toe=this.polishCreateSvg("circle");this.polishSetAttributes(toe,{cx:String(cx),cy:String(cy),r:"1.5",fill:color});badge.appendChild(toe);});}else if(type==="robot"){const b=this.polishCreateSvg("rect");this.polishSetAttributes(b,{x:"-5",y:"-4",width:"10",height:"8",rx:"2",fill:color});badge.appendChild(b);[-2.2,2.2].forEach(cx=>{const e=this.polishCreateSvg("circle");this.polishSetAttributes(e,{cx:String(cx),cy:"-1",r:"1",fill:"var(--card-background-color, #ffffff)"});badge.appendChild(e);});}else if(type==="vehicle"){const b=this.polishCreateSvg("rect");this.polishSetAttributes(b,{x:"-5.5",y:"-2.5",width:"11",height:"5",rx:"1.5",fill:color});badge.appendChild(b);}else{const d=this.polishCreateSvg("path");this.polishSetAttributes(d,{d:"M 0 -6 L 5 0 L 0 6 L -5 0 Z",fill:color});badge.appendChild(d);}w.appendChild(badge);}
 private polishSyncPresenceVisuals():void{const visible=this.presences.filter(p=>p.visible!==false),elements=Array.from(this.renderRoot.querySelectorAll<SVGGElement>("g.presence")),offsets=this.polishOffsets(visible);visible.forEach((p,index)=>{const el=elements[index];if(!el)return;const type=p.type??"person",color=this.polishPresenceColor(p),offset=offsets.get(p.id)??{x:0,y:0,groupSize:1};el.setAttribute("data-presence-id",p.id);el.setAttribute("data-presence-type",type);if(type==="person")el.setAttribute("data-trail-style",String(this.polishPersonTrailVariant(p)+1));el.classList.add("presence-polished",`presence-${type}`);let w=el.querySelector<SVGGElement>(":scope > g.presence-visual-offset");if(!w){w=this.polishCreateSvg("g");w.setAttribute("class","presence-visual-offset");Array.from(el.children).filter(c=>c.localName.toLowerCase()!=="animatetransform").forEach(c=>w?.appendChild(c));el.insertBefore(w,el.firstChild);}w.setAttribute("transform",`translate(${offset.x} ${offset.y})`);w.querySelector<SVGElement>(".presence-marker")?.setAttribute("fill",color);w.querySelector<SVGElement>(".presence-avatar-background")?.setAttribute("fill",color);w.querySelector<SVGElement>(".presence-border")?.setAttribute("stroke",color);this.polishAppendTypeBadge(w,p,color);el.querySelector(":scope > title")?.remove();const title=this.polishCreateSvg("title"),groupText=offset.groupSize>1?` · ${offset.groupSize} markører overlapper`:"",trailText=type==="person"?` · fodspor ${this.polishPersonTrailVariant(p)+1}`:"";title.textContent=`${p.name??p.id} · ${POLISH_TYPE_LABELS[type]}${trailText}${groupText}`;el.appendChild(title);});}
 private polishRouteConfig(){return{type:"custom:ha-explorer-card",rooms:this.rooms,route_nodes:this.routeNodes,route_graph_edges:this.routeGraphEdges,routes:this.routes};}
 private polishMovementPath(from:PolishPosition,to:PolishPosition,fromRoom?:string,toRoom?:string):PolishPosition[]{if(!fromRoom||!toRoom||fromRoom===toRoom)return[from,to];const r=resolveRoute(this.polishRouteConfig(),fromRoom,toRoom,id=>this.hass?.states[id]?.state);if(!r)return[from,to];return[from,...r.hops.slice(1,-1).map(h=>({x:h.point[0]*VIEWBOX_SIZE,y:h.point[1]*VIEWBOX_SIZE})),to];}
 private polishEnsureTrailLayer():SVGGElement|undefined{const scene=this.renderRoot.querySelector<SVGGElement>("g.scene");if(!scene)return;let layer=scene.querySelector<SVGGElement>(":scope > g.presence-trails-scene");if(layer)return layer;layer=this.polishCreateSvg("g");layer.setAttribute("class","presence-trails-scene");layer.setAttribute("aria-label","Person- og objektspor");layer.setAttribute("pointer-events","none");scene.insertBefore(layer,scene.querySelector<SVGGElement>(":scope > g.presences-scene")??null);return layer;}
 private polishTrailSpacing(type:PresenceObjectType,personVariant=0):number{if(type==="person")return PERSON_TRAIL_SPACING[personVariant]??PERSON_TRAIL_SPACING[0];return type==="pet"?46:type==="robot"?42:type==="vehicle"?54:type==="object"?62:58;}
 private polishAppendPersonTrailShape(mark:SVGGElement,color:string,variant:number):void{
  const ellipse=(cx:number,cy:number,rx:number,ry:number)=>{const e=this.polishCreateSvg("ellipse");this.polishSetAttributes(e,{cx:String(cx),cy:String(cy),rx:String(rx),ry:String(ry),fill:color});mark.appendChild(e);};
  if(variant===0){ellipse(0,-5,5.5,11);ellipse(0,8,4,5);return;}
  if(variant===1){ellipse(0,-4,4.2,12);ellipse(0,9,3.2,4.5);return;}
  if(variant===2){ellipse(0,-5,6.5,9.5);const heel=this.polishCreateSvg("rect");this.polishSetAttributes(heel,{x:"-5",y:"3",width:"10",height:"10",rx:"2",fill:color});mark.appendChild(heel);return;}
  if(variant===3){const sole=this.polishCreateSvg("path");this.polishSetAttributes(sole,{d:"M 0 -16 C 6 -10 7 -2 5 5 C 4 10 2 12 0 12 C -3 12 -5 9 -5 4 C -6 -3 -5 -10 0 -16 Z",fill:color});mark.appendChild(sole);ellipse(-.5,9,3.3,4.2);return;}
  if(variant===4){ellipse(0,-9,5.5,6.5);const mid=this.polishCreateSvg("rect");this.polishSetAttributes(mid,{x:"-4",y:"-2",width:"8",height:"7",rx:"3",fill:color});mark.appendChild(mid);ellipse(0,9,3.8,4.5);return;}
  const curved=this.polishCreateSvg("path");this.polishSetAttributes(curved,{d:"M -6 -10 C -2 -15 5 -14 7 -8 C 9 -2 6 5 3 9 C 0 13 -4 12 -5 7 C -6 2 -8 -5 -6 -10 Z",fill:color});mark.appendChild(curved);ellipse(-1,9,3.2,4.1);
 }
 private polishAppendTrailShape(mark:SVGGElement,type:PresenceObjectType,color:string,personVariant=0):void{if(type==="person"){this.polishAppendPersonTrailShape(mark,color,personVariant);return;}if(type==="pet"){const pad=this.polishCreateSvg("ellipse");this.polishSetAttributes(pad,{cx:"0",cy:"2",rx:"5",ry:"6",fill:color});mark.appendChild(pad);return;}if(type==="robot"){[-7,3].forEach(x=>{const t=this.polishCreateSvg("rect");this.polishSetAttributes(t,{x:String(x),y:"-8",width:"4",height:"16",rx:"1.4",fill:color});mark.appendChild(t);});return;}if(type==="vehicle"){[-7,4].forEach(x=>{const t=this.polishCreateSvg("rect");this.polishSetAttributes(t,{x:String(x),y:"-11",width:"3",height:"22",rx:"1",fill:color});mark.appendChild(t);});return;}const d=this.polishCreateSvg("path");this.polishSetAttributes(d,{d:"M 0 -7 L 6 0 L 0 7 L -6 0 Z",fill:color});mark.appendChild(d);}
 private polishCreateTrail(path:PolishPosition[],p:ExplorerPresence):void{if(p.trail_visible===false)return;const layer=this.polishEnsureTrailLayer();if(!layer||path.length<2)return;const type=p.type??"person",personVariant=type==="person"?this.polishPersonTrailVariant(p):0,color=this.polishTrailColor(p),lifetime=this.polishTrailDuration(p),segments=path.slice(1).map((point,index)=>{const start=path[index];return{start,end:point,length:Math.hypot(point.x-start.x,point.y-start.y)};}),total=segments.reduce((s,x)=>s+x.length,0),spacing=this.polishTrailSpacing(type,personVariant);if(total<spacing)return;const count=Math.min(24,Math.max(3,Math.floor(total/spacing)));for(let index=0;index<count;index+=1){const progress=(index+1)/(count+1),target=total*progress;let traversed=0,segment=segments[segments.length-1];for(const c of segments){if(traversed+c.length>=target){segment=c;break;}traversed+=c.length;}const local=segment.length>0?(target-traversed)/segment.length:0,dx=segment.end.x-segment.start.x,dy=segment.end.y-segment.start.y,side=index%2===0?-1:1,alternating=type==="person"?(PERSON_TRAIL_LATERAL[personVariant]??8):type==="pet"?6:0,wobble=type==="person"?(PERSON_TRAIL_WOBBLE[personVariant]??7):alternating?7:0,px=segment.length>0?-dy/segment.length:0,py=segment.length>0?dx/segment.length:0,x=segment.start.x+dx*local+px*alternating*side,y=segment.start.y+dy*local+py*alternating*side,angle=Math.atan2(dy,dx)*180/Math.PI+90,delay=Math.round(progress*POLISH_MOVEMENT_DURATION_MS),mark=this.polishCreateSvg("g");mark.setAttribute("class",`trail-mark trail-${type}${type==="person"?` trail-person-v${personVariant+1}`:""}`);mark.setAttribute("data-presence-id",p.id);if(type==="person")mark.setAttribute("data-trail-style",String(personVariant+1));mark.setAttribute("transform",`translate(${x} ${y}) rotate(${angle+(alternating?side*wobble:0)})`);mark.setAttribute("opacity","0");this.polishAppendTrailShape(mark,type,color,personVariant);const fade=this.polishCreateSvg("animate");this.polishSetAttributes(fade,{attributeName:"opacity",values:"0;0.78;0.54;0",keyTimes:"0;0.08;0.58;1",begin:"indefinite",dur:`${lifetime}ms`,fill:"freeze"});mark.appendChild(fade);layer.appendChild(mark);window.setTimeout(()=>{if(mark.isConnected)(fade as SVGAnimationElement).beginElement();},delay);window.setTimeout(()=>mark.remove(),delay+lifetime+120);}}
 private polishSyncTrails():void{const visible=this.presences.filter(p=>p.visible!==false),reduce=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches??false,currentIds=new Set<string>();visible.forEach(p=>{const current=this.polishBasePosition(p),previous=this.polishPreviousPositions.get(p.id),previousRoom=this.polishPreviousRooms.get(p.id),currentRoom=p.room_id;currentIds.add(p.id);if(!reduce&&previous&&(Math.abs(previous.x-current.x)>.01||Math.abs(previous.y-current.y)>.01))this.polishCreateTrail(this.polishMovementPath(previous,current,previousRoom,currentRoom),p);this.polishPreviousPositions.set(p.id,current);this.polishPreviousRooms.set(p.id,currentRoom);});for(const id of this.polishPreviousPositions.keys())if(!currentIds.has(id)){this.polishPreviousPositions.delete(id);this.polishPreviousRooms.delete(id);}}
 private polishHistoryDurationMs():number{return polishClamp(this.movementHistory.duration_minutes??3,1,5)*60_000;}
 private polishRemoveHistoryLayers():void{const scene=this.renderRoot.querySelector<SVGGElement>("g.scene");scene?.querySelector(":scope > g.movement-history-rooms-scene")?.remove();scene?.querySelector(":scope > g.movement-history-scene")?.remove();}
 private polishScheduleHistoryRefresh():void{if(this.movementHistoryTimer!==undefined)window.clearTimeout(this.movementHistoryTimer);if(this.movementHistory.enabled!==true)return;this.movementHistoryTimer=window.setTimeout(()=>{this.movementHistoryTimer=undefined;this.polishSyncMovementHistory();},5000);}
 private polishSyncMovementHistory():void{if(this.movementHistory.enabled!==true){this.movementHistorySamples.clear();this.polishRemoveHistoryLayers();this.polishScheduleHistoryRefresh();return;}const now=Date.now(),duration=this.polishHistoryDurationMs(),cutoff=now-duration,people=this.presences.filter(p=>p.visible!==false&&(p.type??"person")==="person"),activeIds=new Set(people.map(p=>p.id));for(const [id,samples] of this.movementHistorySamples){if(!activeIds.has(id)){this.movementHistorySamples.delete(id);continue;}const fresh=samples.filter(sample=>sample.at>=cutoff);if(fresh.length)this.movementHistorySamples.set(id,fresh);else this.movementHistorySamples.delete(id);}for(const person of people){const current=this.polishBasePosition(person),samples=this.movementHistorySamples.get(person.id)??[],last=samples[samples.length-1],moved=!last||Math.hypot(last.x-current.x,last.y-current.y)>10||last.roomId!==person.room_id;if(moved){samples.push({...current,roomId:person.room_id,at:now});this.movementHistorySamples.set(person.id,samples.slice(-120));}}this.polishRenderMovementHistory(people,now,duration);this.polishScheduleHistoryRefresh();}
 private polishRenderMovementHistory(people:ExplorerPresence[],now:number,duration:number):void{const scene=this.renderRoot.querySelector<SVGGElement>("g.scene");if(!scene)return;this.polishRemoveHistoryLayers();const roomLayer=this.polishCreateSvg("g"),trailLayer=this.polishCreateSvg("g");roomLayer.setAttribute("class","movement-history-rooms-scene");trailLayer.setAttribute("class","movement-history-scene");roomLayer.setAttribute("pointer-events","none");trailLayer.setAttribute("pointer-events","none");const byId=new Map(people.map(person=>[person.id,person]));for(const [id,samples] of this.movementHistorySamples){const person=byId.get(id);if(!person||person.trail_visible===false)continue;const color=this.polishTrailColor(person),variant=this.polishPersonTrailVariant(person);if(this.movementHistory.show_rooms!==false){const latestRooms=new Map<string,MovementHistorySample>();for(const sample of samples)if(sample.roomId)latestRooms.set(sample.roomId,sample);for(const [roomId,sample] of latestRooms){const room=this.rooms.find(candidate=>candidate.id===roomId||candidate.area_id===roomId);if(!room||room.points.length<3)continue;const age=now-sample.at,opacity=Math.max(0,.16*(1-age/duration)),polygon=this.polishCreateSvg("polygon");this.polishSetAttributes(polygon,{points:room.points.map(([x,y])=>`${x*VIEWBOX_SIZE},${y*VIEWBOX_SIZE}`).join(" "),fill:color,"fill-opacity":String(opacity),stroke:color,"stroke-opacity":String(opacity*.9),"stroke-width":"2","vector-effect":"non-scaling-stroke","data-presence-id":id});roomLayer.appendChild(polygon);}}for(let index=1;index<samples.length;index+=1){const from=samples[index-1],to=samples[index],path=this.polishMovementPath(from,to,from.roomId,to.roomId),age=now-to.at,opacity=Math.max(0,.72*(1-age/duration));for(let pathIndex=1;pathIndex<path.length;pathIndex+=1){const start=path[pathIndex-1],end=path[pathIndex],dx=end.x-start.x,dy=end.y-start.y,length=Math.hypot(dx,dy),count=Math.min(12,Math.max(1,Math.floor(length/70))),angle=Math.atan2(dy,dx)*180/Math.PI+90;for(let step=1;step<=count;step+=1){const progress=step/(count+1),side=step%2===0?-1:1,px=length>0?-dy/length:0,py=length>0?dx/length:0,mark=this.polishCreateSvg("g");mark.setAttribute("class",`movement-history-mark trail-person-v${variant+1}`);mark.setAttribute("data-presence-id",id);mark.setAttribute("transform",`translate(${start.x+dx*progress+px*6*side} ${start.y+dy*progress+py*6*side}) rotate(${angle+side*4}) scale(.62)`);mark.setAttribute("opacity",String(opacity));this.polishAppendTrailShape(mark,"person",color,variant);trailLayer.appendChild(mark);}}}}const insertion=scene.querySelector<SVGGElement>(":scope > g.presence-trails-scene")??scene.querySelector<SVGGElement>(":scope > g.presences-scene");scene.insertBefore(roomLayer,insertion??null);scene.insertBefore(trailLayer,insertion??null);}
 static override styles=css`${ExplorerZonesCanvas.styles}.footsteps-scene{display:none}.presence-visual-offset{transition:transform 220ms ease}.presence-type-badge{filter:drop-shadow(0 1px 2px rgba(0,0,0,.22))}.presence-trails-scene .trail-mark,.movement-history-scene .movement-history-mark{filter:drop-shadow(0 0 1.2px rgba(0,0,0,.20))}.movement-history-rooms-scene polygon{mix-blend-mode:multiply}.presence-trails-scene .trail-person-v2{opacity:.96}.presence-trails-scene .trail-person-v3{filter:drop-shadow(0 0 1.6px rgba(0,0,0,.24))}.presence-trails-scene .trail-person-v5{filter:drop-shadow(0 0 .8px rgba(0,0,0,.18))}:host([map-theme="enchanted_antique"]) .presence-type-badge{filter:sepia(.35) drop-shadow(0 1px 1px rgba(67,40,22,.28))}:host([map-theme="enchanted_antique"]) .presence-trails-scene .trail-mark,:host([map-theme="enchanted_antique"]) .movement-history-scene .movement-history-mark{mix-blend-mode:multiply;filter:sepia(.28) saturate(.78) drop-shadow(0 0 1px rgba(67,40,22,.28))}:host([map-theme="enchanted_antique"]) .presence-border{stroke-width:4.5px!important}@media(prefers-reduced-motion:reduce){.presence-visual-offset{transition:none}}`;
}
