import { LitElement, css, html, nothing, svg } from "lit";
import { customElement, property, query, state } from "lit/decorators.js";
import type { ExplorerCardConfig, ExplorerRoom, NormalizedPoint } from "../models/config";
import type { AreaRegistryEntry, HomeAssistant } from "../types";
import { HaExplorerCardEditor } from "./explorer-config-editor";

const VIEWBOX_SIZE=1000;
type DrawingMode="idle"|"draw-new"|"redraw"|"anchor";
type AnchorPoint={x:number;y:number};
const clampNormalized=(v:number)=>Math.min(1,Math.max(0,v));
function roomCenter(points:NormalizedPoint[]):AnchorPoint{return points.length?{x:points.reduce((s,p)=>s+p[0],0)/points.length,y:points.reduce((s,p)=>s+p[1],0)/points.length}:{x:.5,y:.5};}
function slugify(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"room";}

@customElement("ha-explorer-room-drawing-editor")
export class HaExplorerRoomDrawingEditor extends LitElement{
 @property({attribute:false}) public hass?:HomeAssistant;
 @state() private roomConfig?:ExplorerCardConfig; @state() private drawingMode:DrawingMode="idle"; @state() private selectedRoomId=""; @state() private pendingPoints:NormalizedPoint[]=[]; @state() private pendingAnchor?:AnchorPoint; @state() private draftRoomName=""; @state() private draftAreaId=""; @state() private draftWidth=""; @state() private draftHeight=""; @state() private drawingAreas:AreaRegistryEntry[]=[]; @state() private drawingAreaError="";
 @query("ha-explorer-card-editor") private baseEditor?:HaExplorerCardEditor;
 public setConfig(config:ExplorerCardConfig){this.roomConfig=config;if(this.selectedRoomId&&!(config.rooms??[]).some(r=>r.id===this.selectedRoomId)){this.selectedRoomId="";this.drawingMode="idle";}}
 protected updated(changed:Map<PropertyKey,unknown>){if(changed.has("hass"))void this.loadDrawingAreas();if((changed.has("roomConfig")||changed.has("hass"))&&this.roomConfig)this.baseEditor?.setConfig(this.roomConfig);}
 private async loadDrawingAreas(){if(!this.hass?.callWS){this.drawingAreas=[];return;}try{this.drawingAreas=[...(await this.hass.callWS<AreaRegistryEntry[]>({type:"config/area_registry/list"}))].sort((a,b)=>a.name.localeCompare(b.name,"da"));}catch{this.drawingAreaError="Home Assistant Areas kunne ikke hentes.";}}
 private handleBaseConfigChanged(e:CustomEvent<{config:ExplorerCardConfig}>){if(!e.detail?.config)return;e.stopPropagation();this.emitConfig(e.detail.config);}
 private emitConfig(config:ExplorerCardConfig){this.roomConfig=config;this.baseEditor?.setConfig(config);this.dispatchEvent(new CustomEvent("config-changed",{detail:{config},bubbles:true,composed:true}));}
 private get rooms(){return this.roomConfig?.rooms??[];} private get selectedRoom(){return this.rooms.find(r=>r.id===this.selectedRoomId);}
 private mapPoint(e:MouseEvent):NormalizedPoint{const r=(e.currentTarget as SVGSVGElement).getBoundingClientRect();return r.width&&r.height?[clampNormalized((e.clientX-r.left)/r.width),clampNormalized((e.clientY-r.top)/r.height)]:[.5,.5];}
 private handleMapClick(e:MouseEvent){const p=this.mapPoint(e);if(this.drawingMode==="draw-new"||this.drawingMode==="redraw")this.pendingPoints=[...this.pendingPoints,p];else if(this.drawingMode==="anchor"&&this.selectedRoom)this.pendingAnchor={x:p[0],y:p[1]};}
 private selectRoom(e:MouseEvent,id:string){if(this.drawingMode!=="idle")return;e.stopPropagation();this.selectedRoomId=id;const r=this.rooms.find(x=>x.id===id);this.draftWidth=r?.physical_meters?.width?.toString()??"";this.draftHeight=r?.physical_meters?.height?.toString()??"";}
 private uniqueRoomId(name:string){const b=slugify(name),used=new Set(this.rooms.map(r=>r.id));if(!used.has(b))return b;let n=2;while(used.has(`${b}_${n}`))n++;return `${b}_${n}`;}
 private beginNewRoom(){this.selectedRoomId="";this.pendingPoints=[];this.pendingAnchor=undefined;this.draftRoomName=`Rum ${this.rooms.length+1}`;this.draftAreaId="";this.draftWidth="";this.draftHeight="";this.drawingMode="draw-new";}
 private beginRedraw(){if(this.selectedRoom){this.pendingPoints=[];this.drawingMode="redraw";}}
 private beginAnchor(){if(this.selectedRoom){this.pendingAnchor=undefined;this.drawingMode="anchor";}}
 private cancelDrawing(){this.pendingPoints=[];this.pendingAnchor=undefined;this.drawingMode="idle";}
 private undoPoint(){this.pendingPoints=this.pendingPoints.slice(0,-1);}
 private meters(){const width=Number(this.draftWidth.replace(",",".")),height=Number(this.draftHeight.replace(",","."));return width>0&&height>0?{width,height}:undefined;}
 private finishPolygon(){if(this.pendingPoints.length<3||!this.roomConfig)return;if(this.drawingMode==="draw-new"){const name=this.draftRoomName.trim()||`Rum ${this.rooms.length+1}`,id=this.uniqueRoomId(name),center=roomCenter(this.pendingPoints);const room:ExplorerRoom={id,name,points:this.pendingPoints,presence_anchor:center,...(this.draftAreaId?{area_id:this.draftAreaId}:{}),...(this.meters()?{physical_meters:this.meters()}: {})};this.selectedRoomId=id;this.emitConfig({...this.roomConfig,rooms:[...this.rooms,room]});}else if(this.selectedRoom){this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,points:this.pendingPoints}:r)});}this.pendingPoints=[];this.drawingMode="idle";}
 private saveMeters(){if(!this.roomConfig||!this.selectedRoom)return;const physical_meters=this.meters();if(!physical_meters)return;this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,physical_meters}:r)});}
 private finishAnchor(){if(!this.roomConfig||!this.selectedRoom||!this.pendingAnchor)return;this.emitConfig({...this.roomConfig,rooms:this.rooms.map(r=>r.id===this.selectedRoomId?{...r,presence_anchor:{...this.pendingAnchor!}}:r)});this.pendingAnchor=undefined;this.drawingMode="idle";}
 private renderRoomPolygon(room:ExplorerRoom){if(!room.points.length)return nothing;const pts=room.points.map(([x,y])=>`${x*VIEWBOX_SIZE},${y*VIEWBOX_SIZE}`).join(" "),selected=room.id===this.selectedRoomId,c=roomCenter(room.points),a=selected&&this.drawingMode==="anchor"&&this.pendingAnchor?this.pendingAnchor:(room.presence_anchor??c);return svg`<g style=${this.drawingMode==="idle"?"pointer-events:auto":"pointer-events:none"} @click=${(e:MouseEvent)=>this.selectRoom(e,room.id)}><polygon points=${pts} fill="var(--primary-color,#03a9f4)" fill-opacity=${selected?".30":".14"} stroke="var(--primary-color,#03a9f4)" stroke-width=${selected?7:4}/><text x=${c.x*1000} y=${c.y*1000} text-anchor="middle" dominant-baseline="middle">${room.name??room.id}</text>${selected?svg`<circle cx=${a.x*1000} cy=${a.y*1000} r="15" class="anchor"/>`:nothing}</g>`;}
 private renderPending(){if(!this.pendingPoints.length)return nothing;const pts=this.pendingPoints.map(([x,y])=>`${x*1000},${y*1000}`).join(" ");return svg`${this.pendingPoints.length>=3?svg`<polygon points=${pts} class="pending-fill"/>`:nothing}<polyline points=${pts} class="pending-line" fill="none"/>${this.pendingPoints.map(([x,y],i)=>svg`<circle cx=${x*1000} cy=${y*1000} r="13" class="pending-point"/><text x=${x*1000} y=${y*1000-22} text-anchor="middle">${i+1}</text>`)}`;}
 private dimensionFields(){return html`<div class="dimensions"><label>Bredde (m)<input inputmode="decimal" placeholder="4,3" .value=${this.draftWidth} @input=${(e:InputEvent)=>this.draftWidth=(e.target as HTMLInputElement).value}></label><label>Længde (m)<input inputmode="decimal" placeholder="5,4" .value=${this.draftHeight} @input=${(e:InputEvent)=>this.draftHeight=(e.target as HTMLInputElement).value}></label>${this.drawingMode==="idle"&&this.selectedRoom?html`<button class="primary" ?disabled=${!this.meters()} @click=${this.saveMeters}>Gem fysiske mål</button>`:nothing}</div>`;}
 protected render(){if(!this.roomConfig)return nothing;const image=this.roomConfig.image??this.roomConfig.background??"",preserve=this.roomConfig.fit_mode==="cover"?"xMidYMid slice":"xMidYMid meet";return html`<ha-explorer-card-editor .hass=${this.hass} @config-changed=${this.handleBaseConfigChanged}></ha-explorer-card-editor><section class="drawing-editor"><div class="heading"><div><small>VISUAL ROOM CALIBRATION · v0.31</small><h3>Tegn og mål rum direkte på plantegningen</h3></div><b>${this.rooms.length} rum</b></div><div class="instruction">${this.drawingMode==="idle"?"Vælg et rum eller opret et nyt. Tegn kanten og angiv rummets virkelige mål i meter.":this.drawingMode==="anchor"?"Klik hvor personpunktet skal være.":"Klik rundt langs rummets kant. Mindst 3 punkter."}</div>${this.drawingMode==="draw-new"?html`<div class="grid"><label>Rumnavn<input .value=${this.draftRoomName} @input=${(e:InputEvent)=>this.draftRoomName=(e.target as HTMLInputElement).value}></label><label>Home Assistant Area<select .value=${this.draftAreaId} @change=${(e:Event)=>this.draftAreaId=(e.target as HTMLSelectElement).value}><option value="">Ikke bundet</option>${this.drawingAreas.map(a=>html`<option value=${a.area_id}>${a.name}</option>`)}</select></label></div>${this.dimensionFields()}`:this.selectedRoom&&this.drawingMode==="idle"?html`<div class="selected"><strong>${this.selectedRoom.name??this.selectedRoom.id}</strong><span>${this.selectedRoom.points.length} punkter${this.selectedRoom.physical_meters?` · ${this.selectedRoom.physical_meters.width} × ${this.selectedRoom.physical_meters.height} m`:" · mangler fysiske mål"}</span></div>${this.dimensionFields()}`:nothing}${this.drawingAreaError?html`<div class="warning">${this.drawingAreaError}</div>`:nothing}${image?html`<div class="map-frame"><svg viewBox="0 0 1000 1000" preserveAspectRatio="none" @click=${this.handleMapClick}><image href=${image} width="1000" height="1000" preserveAspectRatio=${preserve}/>${this.rooms.map(r=>this.renderRoomPolygon(r))}${this.renderPending()}</svg></div>`:html`<div class="instruction">Vælg først en plantegning under Kort.</div>`}<div class="buttons">${this.drawingMode==="draw-new"||this.drawingMode==="redraw"?html`<button @click=${this.undoPoint}>Fortryd punkt</button><button class="primary" ?disabled=${this.pendingPoints.length<3||(this.drawingMode==="draw-new"&&!this.meters())} @click=${this.finishPolygon}>Gem rum</button><button @click=${this.cancelDrawing}>Annuller</button>`:this.drawingMode==="anchor"?html`<button class="primary" ?disabled=${!this.pendingAnchor} @click=${this.finishAnchor}>Gem personpunkt</button><button @click=${this.cancelDrawing}>Annuller</button>`:html`<button class="primary" @click=${this.beginNewRoom}>+ Nyt rum</button><button ?disabled=${!this.selectedRoom} @click=${this.beginRedraw}>Tegn rumkant igen</button><button ?disabled=${!this.selectedRoom} @click=${this.beginAnchor}>Placér personpunkt</button>`}</div></section>`;}
 static styles=css`:host{display:block}.drawing-editor{margin-top:18px;display:grid;gap:14px;padding:16px;border:1px solid var(--divider-color);border-radius:14px;background:var(--ha-card-background,var(--card-background-color))}.heading{display:flex;justify-content:space-between;gap:12px}.heading h3{margin:3px 0}.heading small{color:var(--secondary-text-color);font-weight:700;letter-spacing:.1em}.instruction,.selected,.warning{padding:10px 12px;border-radius:10px;background:var(--secondary-background-color);color:var(--secondary-text-color)}.grid,.dimensions{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;align-items:end}label{display:grid;gap:5px;font-size:.8rem;color:var(--secondary-text-color)}input,select{box-sizing:border-box;width:100%;padding:9px;border:1px solid var(--divider-color);border-radius:8px;background:var(--card-background-color);color:var(--primary-text-color)}.map-frame{overflow:hidden;border:1px solid var(--divider-color);border-radius:12px;background:var(--secondary-background-color)}svg{display:block;width:100%;height:min(58vh,620px);cursor:crosshair}text{fill:var(--primary-text-color);font-size:24px;font-weight:700}.pending-fill{fill:var(--primary-color);fill-opacity:.18;stroke:var(--primary-color);stroke-width:5}.pending-line{stroke:var(--primary-color);stroke-width:6}.pending-point,.anchor{fill:var(--primary-color);stroke:white;stroke-width:4}.buttons{display:flex;flex-wrap:wrap;gap:8px}button{padding:9px 13px;border:1px solid var(--divider-color);border-radius:9px;background:var(--secondary-background-color);color:var(--primary-text-color);cursor:pointer}button.primary{background:var(--primary-color);color:var(--text-primary-color,#fff);border-color:var(--primary-color)}button:disabled{opacity:.45;cursor:not-allowed}.selected{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}`;
}
